export const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_MASTER: 'COMPANY_MASTER',
  RAILWAY_MASTER: 'RAILWAY_MASTER',
  ADMIN: 'ADMIN',
  RAILWAY_ADMIN: 'RAILWAY_ADMIN',
  RAILWAY_INSPECTOR: 'RAILWAY_INSPECTOR',
  RAILWAY_SUPERVISOR: 'RAILWAY_SUPERVISOR',
  CONTRACTOR_MASTER: 'CONTRACTOR_MASTER',
  CONTRACTOR_ADMIN: 'CONTRACTOR_ADMIN',
  CONTRACTOR_SUPERVISOR: 'CONTRACTOR_SUPERVISOR',
  CTS: 'CTS',
  WORKER: 'WORKER',
  RAILWAY_WORKER: 'RAILWAY_WORKER',
  JANITOR: 'JANITOR',
  ATTENDANT: 'ATTENDANT',
  PASSENGER: 'PASSENGER'
});

export const ROLE_HIERARCHY = Object.freeze({
  SUPER_ADMIN: 100,
  COMPANY_MASTER: 90,
  RAILWAY_MASTER: 80,
  ADMIN: 70,
  RAILWAY_ADMIN: 60,
  RAILWAY_INSPECTOR: 52,
  RAILWAY_SUPERVISOR: 50,
  CONTRACTOR_MASTER: 47,
  CONTRACTOR_ADMIN: 45,
  CONTRACTOR_SUPERVISOR: 40,
  CTS: 30,
  WORKER: 10,
  RAILWAY_WORKER: 10,
  JANITOR: 10,
  ATTENDANT: 10,
  PASSENGER: 1
});

export const PERMISSIONS = Object.freeze({
  // User management
  CREATE_USER: 'create_user',
  UPDATE_USER: 'update_user',
  APPROVE_USER: 'approve_user',
  REJECT_USER: 'reject_user',
  SUSPEND_USER: 'suspend_user',
  VIEW_USERS: 'view_users',
  VIEW_USER_DETAILS: 'view_user_details',

  // Entity management
  CREATE_ENTITY: 'create_entity',
  UPDATE_ENTITY: 'update_entity',
  APPROVE_ENTITY: 'approve_entity',
  REJECT_ENTITY: 'reject_entity',
  SUSPEND_ENTITY: 'suspend_entity',
  VIEW_ENTITIES: 'view_entities',

  // Contract management
  CREATE_CONTRACT: 'create_contract',
  UPDATE_CONTRACT: 'update_contract',
  VIEW_CONTRACTS: 'view_contracts',

  // Train management
  CREATE_TRAIN: 'create_train',
  UPDATE_TRAIN: 'update_train',
  VIEW_TRAINS: 'view_trains',

  // Run instances
  CREATE_RUN_INSTANCE: 'create_run_instance',
  UPDATE_RUN_INSTANCE: 'update_run_instance',
  ACTIVATE_JOURNEY: 'activate_journey',
  COMPLETE_JOURNEY: 'complete_journey',
  VIEW_RUN_INSTANCES: 'view_run_instances',

  // Forms
  SUBMIT_COACH_FORM: 'submit_coach_form',
  APPROVE_FORM_MANPOWER: 'approve_form_manpower',
  SCORE_FORM: 'score_form',
  ACCEPT_RATING: 'accept_rating',
  REJECT_FORM: 'reject_form',
  VIEW_FORMS: 'view_forms',

  // Emergency
  CREATE_EMERGENCY_TASK: 'create_emergency_task',

  // Reports
  VIEW_REPORTS: 'view_reports',
  GENERATE_REPORTS: 'generate_reports',

  MANAGE_PLATFORMS: 'manage_platforms',
  VIEW_PLATFORMS: 'view_platforms',

  MANAGE_AREAS: 'manage_areas',
  VIEW_AREAS: 'view_areas',

  // Frequency Configuration
  MANAGE_FREQUENCIES: 'manage_frequencies',
  VIEW_FREQUENCIES: 'view_frequencies',
  GENERATE_TASKS: 'generate_tasks',
  CALCULATE_FREQUENCY: 'calculate_frequency',

  // Shift Management
  MANAGE_SHIFTS: 'manage_shifts',
  VIEW_SHIFTS: 'view_shifts',
  ASSIGN_SHIFT: 'assign_shift',

  // Deployment
  MANAGE_DEPLOYMENTS: 'manage_deployments',
  VIEW_DEPLOYMENTS: 'view_deployments',

  // Geofence
  MANAGE_GEOFENCES: 'manage_geofences',
  VIEW_GEOFENCES: 'view_geofences',

  // Inspection
  MANAGE_INSPECTIONS: 'manage_inspections',
  VIEW_INSPECTIONS: 'view_inspections',
  APPROVE_INSPECTION: 'approve_inspection',
  SCORE_INSPECTION: 'score_inspection',

  // Petty Issue
  MANAGE_PETTY_ISSUES: 'manage_petty_issues',
  VIEW_PETTY_ISSUES: 'view_petty_issues',
  RESOLVE_PETTY_ISSUE: 'resolve_petty_issue',

  // Activity
  MANAGE_ACTIVITIES: 'manage_activities',
  VIEW_ACTIVITIES: 'view_activities',

  // Machine
  MANAGE_MACHINES: 'manage_machines',
  VIEW_MACHINES: 'view_machines',

  // Material
  MANAGE_MATERIALS: 'manage_materials',
  VIEW_MATERIALS: 'view_materials',

  // Pest Control
  MANAGE_PEST_CONTROL: 'manage_pest_control',
  VIEW_PEST_CONTROL: 'view_pest_control',

  // Garbage
  MANAGE_GARBAGE: 'manage_garbage',
  VIEW_GARBAGE: 'view_garbage',

  // Complaint
  CREATE_COMPLAINT: 'create_complaint',
  VIEW_COMPLAINTS: 'view_complaints',
  MANAGE_COMPLAINTS: 'manage_complaints',

  // Forms management (for feedback moderation)
  MANAGE_FORMS: 'manage_forms',

  // Reports management
  MANAGE_REPORTS: 'manage_reports',
  MANAGE_REPORT_SCHEDULES: 'manage_report_schedules',

  // Scorecard
  MANAGE_SCORECARDS: 'manage_scorecards',
  VIEW_SCORECARDS: 'view_scorecards',
  APPROVE_SCORECARDS: 'approve_scorecards',

  // Supervisor Daily Log
  MANAGE_SUPERVISOR_LOGS: 'manage_supervisor_logs',
  VIEW_SUPERVISOR_LOGS: 'view_supervisor_logs',

  // Execution
  MANAGE_EXECUTION: 'manage_execution',
  VIEW_EXECUTION: 'view_execution',
  APPROVE_EXECUTION: 'approve_execution',

  // Station Cleaning Runs
  MANAGE_RUNS: 'manage_runs',
  VIEW_RUNS: 'view_runs',

  // Station Tasks
  SUBMIT_TASKS: 'submit_tasks',
  VIEW_TASKS: 'view_tasks',
  START_TASK: 'start_task',
  COMPLETE_TASK: 'complete_task',
  RESUBMIT_TASK: 'resubmit_task',
  APPROVE_TASK: 'approve_task',
  REJECT_TASK: 'reject_task',

  // Area Assignments
  MANAGE_AREA_ASSIGNMENTS: 'manage_area_assignments',
  VIEW_AREA_ASSIGNMENTS: 'view_area_assignments',

  // Station Schedules
  MANAGE_SCHEDULES: 'manage_schedules',
  VIEW_SCHEDULES: 'view_schedules',

  // Station Dashboard
  VIEW_DASHBOARD: 'view_dashboard',

  // Contractor Mappings
  MANAGE_CONTRACTORS: 'manage_contractors',
  VIEW_CONTRACTORS: 'view_contractors',

  // Station Feedback
  VIEW_FEEDBACK: 'view_feedback',
  SUBMIT_FEEDBACK: 'submit_feedback',

  // Search
  VIEW_SEARCH: 'view_search',

  // Station
  MANAGE_STATIONS: 'manage_stations',
  VIEW_STATIONS: 'view_stations',

  // Station Archives
  MANAGE_ARCHIVES: 'manage_archives',
  VIEW_ARCHIVES: 'view_archives',

  // Admin
  VIEW_ANALYTICS: 'view_analytics',
  MANAGE_SYSTEM: 'manage_system',
  VIEW_SYSTEM: 'view_system',

  // Billing
  GENERATE_BILLING: 'generate_billing',
  VIEW_BILLING: 'view_billing',
  MANAGE_BILLING: 'manage_billing',
  APPROVE_BILLING: 'approve_billing',
  RECORD_PAYMENT: 'record_payment',

  // Passenger Service Request
  MANAGE_PASSENGER_REQUESTS: 'manage_passenger_requests',
  VIEW_PASSENGER_REQUESTS: 'view_passenger_requests',
  CREATE_PASSENGER_REQUEST: 'create_passenger_request',
  VIEW_PASSENGER_REQUEST_ANALYTICS: 'view_passenger_request_analytics',

  // Station Cleaning Workforce
  MANAGE_WORKFORCE: 'manage_workforce',
  VIEW_WORKFORCE: 'view_workforce',

  // Station Cleaning Submissions
  MANAGE_SUBMISSIONS: 'manage_submissions',
  VIEW_SUBMISSIONS: 'view_submissions',

  // Shift Summary (work history report for billing)
  VIEW_SHIFT_SUMMARIES: 'view_shift_summaries',
  APPROVE_SHIFT_SUMMARY: 'approve_shift_summary',
  REJECT_SHIFT_SUMMARY: 'reject_shift_summary'
});

export const ROLE_PERMISSIONS = Object.freeze({
  SUPER_ADMIN: Object.values(PERMISSIONS),

  PASSENGER: [
    PERMISSIONS.SUBMIT_FEEDBACK
  ],

  COMPANY_MASTER: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER, PERMISSIONS.APPROVE_USER,
    PERMISSIONS.REJECT_USER, PERMISSIONS.SUSPEND_USER, PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.CREATE_ENTITY, PERMISSIONS.UPDATE_ENTITY,
    PERMISSIONS.APPROVE_ENTITY, PERMISSIONS.REJECT_ENTITY, PERMISSIONS.SUSPEND_ENTITY,
    PERMISSIONS.VIEW_ENTITIES, PERMISSIONS.CREATE_CONTRACT, PERMISSIONS.UPDATE_CONTRACT,
    PERMISSIONS.VIEW_CONTRACTS, PERMISSIONS.CREATE_TRAIN, PERMISSIONS.UPDATE_TRAIN,
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.CREATE_RUN_INSTANCE, PERMISSIONS.UPDATE_RUN_INSTANCE,
    PERMISSIONS.ACTIVATE_JOURNEY, PERMISSIONS.COMPLETE_JOURNEY, PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.MANAGE_REPORTS, PERMISSIONS.MANAGE_REPORT_SCHEDULES,
    PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.MANAGE_SYSTEM, PERMISSIONS.VIEW_SYSTEM,
    PERMISSIONS.MANAGE_PLATFORMS, PERMISSIONS.VIEW_PLATFORMS,
    PERMISSIONS.MANAGE_AREAS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.MANAGE_AREA_ASSIGNMENTS, PERMISSIONS.VIEW_AREA_ASSIGNMENTS,
    PERMISSIONS.MANAGE_FREQUENCIES, PERMISSIONS.VIEW_FREQUENCIES, PERMISSIONS.GENERATE_TASKS,
    PERMISSIONS.MANAGE_SHIFTS, PERMISSIONS.VIEW_SHIFTS, PERMISSIONS.ASSIGN_SHIFT,
    PERMISSIONS.MANAGE_DEPLOYMENTS, PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.MANAGE_GEOFENCES, PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.MANAGE_INSPECTIONS, PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.APPROVE_INSPECTION, PERMISSIONS.SCORE_INSPECTION,
    PERMISSIONS.MANAGE_PETTY_ISSUES, PERMISSIONS.VIEW_PETTY_ISSUES, PERMISSIONS.RESOLVE_PETTY_ISSUE,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.MANAGE_ACTIVITIES, PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.MANAGE_MACHINES, PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.MANAGE_MATERIALS, PERMISSIONS.VIEW_MATERIALS,
    PERMISSIONS.MANAGE_PEST_CONTROL, PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.MANAGE_GARBAGE, PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.CREATE_COMPLAINT, PERMISSIONS.VIEW_COMPLAINTS, PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.MANAGE_SCORECARDS,     PERMISSIONS.MANAGE_FORMS,
    PERMISSIONS.VIEW_SCORECARDS, PERMISSIONS.APPROVE_SCORECARDS,
    PERMISSIONS.MANAGE_STATIONS, PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.MANAGE_ARCHIVES, PERMISSIONS.VIEW_ARCHIVES,
    PERMISSIONS.MANAGE_RUNS, PERMISSIONS.MANAGE_SCHEDULES,
    PERMISSIONS.MANAGE_CONTRACTORS, PERMISSIONS.MANAGE_SUPERVISOR_LOGS,
    PERMISSIONS.MANAGE_EXECUTION, PERMISSIONS.SUBMIT_COACH_FORM, PERMISSIONS.SUBMIT_TASKS,
    PERMISSIONS.MANAGE_SUPERVISOR_LOGS, PERMISSIONS.VIEW_SUPERVISOR_LOGS,
    PERMISSIONS.MANAGE_EXECUTION, PERMISSIONS.VIEW_EXECUTION, PERMISSIONS.APPROVE_EXECUTION,
    PERMISSIONS.MANAGE_RUNS, PERMISSIONS.VIEW_RUNS,
    PERMISSIONS.VIEW_TASKS, PERMISSIONS.SUBMIT_TASKS,
    PERMISSIONS.APPROVE_TASK, PERMISSIONS.REJECT_TASK,
    PERMISSIONS.MANAGE_SCHEDULES, PERMISSIONS.VIEW_SCHEDULES,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_CONTRACTORS, PERMISSIONS.VIEW_CONTRACTORS,
    PERMISSIONS.VIEW_FEEDBACK,
    PERMISSIONS.MANAGE_STATIONS, PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.MANAGE_ARCHIVES, PERMISSIONS.VIEW_ARCHIVES,
    PERMISSIONS.GENERATE_BILLING, PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.MANAGE_BILLING, PERMISSIONS.APPROVE_BILLING, PERMISSIONS.RECORD_PAYMENT,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.VIEW_SUBMISSIONS
  ],

  RAILWAY_MASTER: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER, PERMISSIONS.APPROVE_USER,
    PERMISSIONS.REJECT_USER, PERMISSIONS.SUSPEND_USER, PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_ENTITIES, PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.MANAGE_REPORTS, PERMISSIONS.MANAGE_REPORT_SCHEDULES,
    PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.MANAGE_SYSTEM, PERMISSIONS.VIEW_SYSTEM,
    PERMISSIONS.VIEW_PLATFORMS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.VIEW_FREQUENCIES,
    PERMISSIONS.VIEW_SHIFTS,
    PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VIEW_PETTY_ISSUES,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.VIEW_MATERIALS,
    PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.VIEW_COMPLAINTS,
    PERMISSIONS.VIEW_SCORECARDS,
    PERMISSIONS.VIEW_SUPERVISOR_LOGS,
    PERMISSIONS.VIEW_EXECUTION,
    PERMISSIONS.VIEW_RUNS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.VIEW_SCHEDULES,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CONTRACTORS,
    PERMISSIONS.VIEW_FEEDBACK,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.VIEW_ARCHIVES,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_SHIFT_SUMMARIES,
    PERMISSIONS.APPROVE_SHIFT_SUMMARY, PERMISSIONS.REJECT_SHIFT_SUMMARY
  ],


  ADMIN: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER, PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_ENTITIES, PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.VIEW_FORMS,
    PERMISSIONS.VIEW_REPORTS, PERMISSIONS.UPDATE_RUN_INSTANCE,
    PERMISSIONS.MANAGE_PLATFORMS, PERMISSIONS.VIEW_PLATFORMS,
    PERMISSIONS.MANAGE_AREAS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.MANAGE_FREQUENCIES, PERMISSIONS.VIEW_FREQUENCIES, PERMISSIONS.GENERATE_TASKS,
    PERMISSIONS.MANAGE_SHIFTS, PERMISSIONS.VIEW_SHIFTS, PERMISSIONS.ASSIGN_SHIFT,
    PERMISSIONS.MANAGE_DEPLOYMENTS, PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.MANAGE_GEOFENCES, PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.MANAGE_INSPECTIONS, PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.APPROVE_INSPECTION, PERMISSIONS.SCORE_INSPECTION,
    PERMISSIONS.MANAGE_PETTY_ISSUES, PERMISSIONS.VIEW_PETTY_ISSUES, PERMISSIONS.RESOLVE_PETTY_ISSUE,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.MANAGE_ACTIVITIES, PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.MANAGE_MACHINES, PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.MANAGE_MATERIALS, PERMISSIONS.VIEW_MATERIALS,
    PERMISSIONS.MANAGE_PEST_CONTROL, PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.MANAGE_GARBAGE, PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.CREATE_COMPLAINT, PERMISSIONS.VIEW_COMPLAINTS, PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.MANAGE_FORMS,
    PERMISSIONS.MANAGE_SCORECARDS, PERMISSIONS.VIEW_SCORECARDS, PERMISSIONS.APPROVE_SCORECARDS,
    PERMISSIONS.MANAGE_SUPERVISOR_LOGS, PERMISSIONS.VIEW_SUPERVISOR_LOGS,
    PERMISSIONS.MANAGE_EXECUTION, PERMISSIONS.VIEW_EXECUTION, PERMISSIONS.APPROVE_EXECUTION,
    PERMISSIONS.MANAGE_RUNS, PERMISSIONS.VIEW_RUNS,
    PERMISSIONS.VIEW_TASKS, PERMISSIONS.SUBMIT_TASKS,
    PERMISSIONS.MANAGE_SCHEDULES, PERMISSIONS.VIEW_SCHEDULES,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_CONTRACTORS, PERMISSIONS.VIEW_CONTRACTORS,
    PERMISSIONS.VIEW_FEEDBACK, PERMISSIONS.SUBMIT_COACH_FORM,
    PERMISSIONS.MANAGE_STATIONS, PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.MANAGE_ARCHIVES, PERMISSIONS.VIEW_ARCHIVES,
    PERMISSIONS.GENERATE_BILLING, PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.MANAGE_BILLING, PERMISSIONS.APPROVE_BILLING, PERMISSIONS.RECORD_PAYMENT,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.VIEW_SUBMISSIONS
  ],

  RAILWAY_ADMIN: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER,
    PERMISSIONS.VIEW_USERS, PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_ENTITIES,
    PERMISSIONS.VIEW_CONTRACTS, PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.SUBMIT_COACH_FORM,
    PERMISSIONS.APPROVE_FORM_MANPOWER, PERMISSIONS.SCORE_FORM, PERMISSIONS.REJECT_FORM,
    PERMISSIONS.MANAGE_PLATFORMS, PERMISSIONS.VIEW_PLATFORMS,
    PERMISSIONS.MANAGE_AREAS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.MANAGE_FREQUENCIES, PERMISSIONS.VIEW_FREQUENCIES, PERMISSIONS.GENERATE_TASKS,
    PERMISSIONS.MANAGE_SHIFTS, PERMISSIONS.VIEW_SHIFTS, PERMISSIONS.ASSIGN_SHIFT,
    PERMISSIONS.MANAGE_DEPLOYMENTS, PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.MANAGE_GEOFENCES, PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.MANAGE_INSPECTIONS, PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.APPROVE_INSPECTION, PERMISSIONS.SCORE_INSPECTION,
    PERMISSIONS.MANAGE_PETTY_ISSUES, PERMISSIONS.VIEW_PETTY_ISSUES, PERMISSIONS.RESOLVE_PETTY_ISSUE,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.MANAGE_ACTIVITIES, PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.MANAGE_MACHINES, PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.MANAGE_MATERIALS, PERMISSIONS.VIEW_MATERIALS,
    PERMISSIONS.MANAGE_PEST_CONTROL, PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.MANAGE_GARBAGE, PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.CREATE_COMPLAINT, PERMISSIONS.VIEW_COMPLAINTS, PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.MANAGE_SCORECARDS, PERMISSIONS.VIEW_SCORECARDS, PERMISSIONS.APPROVE_SCORECARDS,
    PERMISSIONS.MANAGE_SUPERVISOR_LOGS, PERMISSIONS.VIEW_SUPERVISOR_LOGS,
    PERMISSIONS.MANAGE_EXECUTION, PERMISSIONS.VIEW_EXECUTION, PERMISSIONS.APPROVE_EXECUTION,
    PERMISSIONS.MANAGE_RUNS, PERMISSIONS.VIEW_RUNS,
    PERMISSIONS.VIEW_TASKS, PERMISSIONS.SUBMIT_TASKS,
    PERMISSIONS.APPROVE_TASK, PERMISSIONS.REJECT_TASK,
    PERMISSIONS.MANAGE_SCHEDULES, PERMISSIONS.VIEW_SCHEDULES,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_CONTRACTORS, PERMISSIONS.VIEW_CONTRACTORS,
    PERMISSIONS.VIEW_FEEDBACK,
    PERMISSIONS.MANAGE_STATIONS, PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.MANAGE_ARCHIVES, PERMISSIONS.VIEW_ARCHIVES,
    PERMISSIONS.GENERATE_BILLING, PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.MANAGE_BILLING, PERMISSIONS.APPROVE_BILLING, PERMISSIONS.RECORD_PAYMENT,
    PERMISSIONS.VIEW_SHIFT_SUMMARIES,
    PERMISSIONS.APPROVE_SHIFT_SUMMARY, PERMISSIONS.REJECT_SHIFT_SUMMARY
  ],

  RAILWAY_INSPECTOR: [
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_PLATFORMS,
    PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.VIEW_FREQUENCIES,
    PERMISSIONS.MANAGE_INSPECTIONS, PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.APPROVE_INSPECTION, PERMISSIONS.SCORE_INSPECTION,
    PERMISSIONS.MANAGE_PETTY_ISSUES, PERMISSIONS.VIEW_PETTY_ISSUES, PERMISSIONS.RESOLVE_PETTY_ISSUE,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.VIEW_SCORECARDS,
    PERMISSIONS.VIEW_TASKS, PERMISSIONS.APPROVE_TASK, PERMISSIONS.REJECT_TASK,
    PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.VIEW_SHIFT_SUMMARIES
  ],

  RAILWAY_SUPERVISOR: [
    PERMISSIONS.VIEW_USERS, PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_TRAINS,
    PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_PLATFORMS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.VIEW_FREQUENCIES,
    PERMISSIONS.VIEW_SHIFTS,
    PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.VIEW_INSPECTIONS, PERMISSIONS.SCORE_INSPECTION,
    PERMISSIONS.VIEW_PETTY_ISSUES, PERMISSIONS.MANAGE_PETTY_ISSUES, PERMISSIONS.RESOLVE_PETTY_ISSUE,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.VIEW_MATERIALS,
    PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.CREATE_COMPLAINT, PERMISSIONS.VIEW_COMPLAINTS,
    PERMISSIONS.VIEW_SCORECARDS,
    PERMISSIONS.MANAGE_SUPERVISOR_LOGS, PERMISSIONS.VIEW_SUPERVISOR_LOGS,
    PERMISSIONS.VIEW_EXECUTION,
    PERMISSIONS.VIEW_RUNS, PERMISSIONS.VIEW_TASKS, PERMISSIONS.SUBMIT_TASKS,
    PERMISSIONS.START_TASK, PERMISSIONS.COMPLETE_TASK,
    PERMISSIONS.APPROVE_TASK, PERMISSIONS.REJECT_TASK,
    PERMISSIONS.VIEW_SCHEDULES,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CONTRACTORS,
    PERMISSIONS.VIEW_FEEDBACK,
    PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.VIEW_ARCHIVES,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.VIEW_SUBMISSIONS,
    PERMISSIONS.VIEW_SHIFT_SUMMARIES,
    PERMISSIONS.APPROVE_SHIFT_SUMMARY, PERMISSIONS.REJECT_SHIFT_SUMMARY
  ],

  CONTRACTOR_ADMIN: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER, PERMISSIONS.APPROVE_USER,
    PERMISSIONS.REJECT_USER, PERMISSIONS.VIEW_USERS, PERMISSIONS.VIEW_USER_DETAILS,
    PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.MANAGE_AREAS, PERMISSIONS.VIEW_AREAS, PERMISSIONS.MANAGE_PLATFORMS, PERMISSIONS.VIEW_PLATFORMS,
    PERMISSIONS.MANAGE_AREA_ASSIGNMENTS, PERMISSIONS.VIEW_AREA_ASSIGNMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SHIFTS, PERMISSIONS.MANAGE_SHIFTS, PERMISSIONS.ASSIGN_SHIFT,
    PERMISSIONS.VIEW_DEPLOYMENTS, PERMISSIONS.MANAGE_DEPLOYMENTS,
    PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.MANAGE_INSPECTIONS, PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.APPROVE_INSPECTION, PERMISSIONS.SCORE_INSPECTION,
    PERMISSIONS.VIEW_PETTY_ISSUES,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.VIEW_MACHINES, PERMISSIONS.MANAGE_MACHINES,
    PERMISSIONS.VIEW_MATERIALS, PERMISSIONS.MANAGE_MATERIALS,
    PERMISSIONS.VIEW_PEST_CONTROL, PERMISSIONS.MANAGE_PEST_CONTROL,
    PERMISSIONS.VIEW_GARBAGE, PERMISSIONS.MANAGE_GARBAGE,
    PERMISSIONS.VIEW_FORMS, PERMISSIONS.APPROVE_FORM_MANPOWER, PERMISSIONS.SCORE_FORM, PERMISSIONS.REJECT_FORM,
    PERMISSIONS.VIEW_SCORECARDS,
    PERMISSIONS.VIEW_SUPERVISOR_LOGS, PERMISSIONS.MANAGE_SUPERVISOR_LOGS,
    PERMISSIONS.VIEW_EXECUTION,
    PERMISSIONS.VIEW_RUNS, PERMISSIONS.MANAGE_RUNS,
    PERMISSIONS.VIEW_TASKS, PERMISSIONS.SUBMIT_TASKS,
    PERMISSIONS.START_TASK, PERMISSIONS.COMPLETE_TASK,
    PERMISSIONS.APPROVE_TASK, PERMISSIONS.REJECT_TASK,
    PERMISSIONS.VIEW_SCHEDULES, PERMISSIONS.MANAGE_SCHEDULES,
    PERMISSIONS.VIEW_FREQUENCIES, PERMISSIONS.MANAGE_FREQUENCIES, PERMISSIONS.GENERATE_TASKS,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CONTRACTORS, PERMISSIONS.MANAGE_CONTRACTORS,
    PERMISSIONS.VIEW_FEEDBACK,
    PERMISSIONS.VIEW_ACTIVITIES, PERMISSIONS.MANAGE_ACTIVITIES,
    PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.MANAGE_ARCHIVES, PERMISSIONS.VIEW_ARCHIVES,
    PERMISSIONS.GENERATE_BILLING, PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.APPROVE_BILLING, PERMISSIONS.RECORD_PAYMENT,
    PERMISSIONS.CREATE_COMPLAINT, PERMISSIONS.VIEW_COMPLAINTS, PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.MANAGE_WORKFORCE, PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.MANAGE_SUBMISSIONS, PERMISSIONS.VIEW_SUBMISSIONS
  ],

  CONTRACTOR_MASTER: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER, PERMISSIONS.APPROVE_USER,
    PERMISSIONS.REJECT_USER, PERMISSIONS.VIEW_USERS, PERMISSIONS.VIEW_USER_DETAILS,
    PERMISSIONS.CREATE_CONTRACT, PERMISSIONS.UPDATE_CONTRACT, PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.MANAGE_AREAS, PERMISSIONS.VIEW_AREAS, PERMISSIONS.MANAGE_PLATFORMS, PERMISSIONS.VIEW_PLATFORMS,
    PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_SHIFTS,
    PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.VIEW_INSPECTIONS, PERMISSIONS.VIEW_PETTY_ISSUES,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.VIEW_MATERIALS,
    PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.VIEW_COMPLAINTS,
    PERMISSIONS.VIEW_SCORECARDS,
    PERMISSIONS.VIEW_SUPERVISOR_LOGS,
    PERMISSIONS.VIEW_EXECUTION,
    PERMISSIONS.VIEW_RUNS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.VIEW_SCHEDULES,
    PERMISSIONS.VIEW_FREQUENCIES,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CONTRACTORS, PERMISSIONS.MANAGE_CONTRACTORS,
    PERMISSIONS.VIEW_FEEDBACK,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.VIEW_ARCHIVES,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.VIEW_STATIONS
  ],

  CONTRACTOR_SUPERVISOR: [
    PERMISSIONS.VIEW_USERS, PERMISSIONS.VIEW_USER_DETAILS,
    PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.VIEW_FORMS,
    PERMISSIONS.VIEW_PLATFORMS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.VIEW_SHIFTS,
    PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VIEW_PETTY_ISSUES,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.VIEW_SCORECARDS,
    PERMISSIONS.VIEW_SUPERVISOR_LOGS,
    PERMISSIONS.VIEW_GARBAGE, PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.VIEW_MATERIALS, PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_RUNS, PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.START_TASK, PERMISSIONS.COMPLETE_TASK, PERMISSIONS.SUBMIT_TASKS, PERMISSIONS.RESUBMIT_TASK,
    PERMISSIONS.VIEW_SCHEDULES,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CONTRACTORS,
    PERMISSIONS.VIEW_FEEDBACK,
    PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.VIEW_ARCHIVES,
    PERMISSIONS.CREATE_COMPLAINT, PERMISSIONS.VIEW_COMPLAINTS,
    PERMISSIONS.MANAGE_WORKFORCE, PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.MANAGE_SUBMISSIONS, PERMISSIONS.VIEW_SUBMISSIONS
  ],

  CTS: [
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.CREATE_EMERGENCY_TASK
  ],

  WORKER: [
    PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.SUBMIT_COACH_FORM,
    PERMISSIONS.VIEW_TASKS, PERMISSIONS.SUBMIT_TASKS,
    PERMISSIONS.START_TASK, PERMISSIONS.COMPLETE_TASK, PERMISSIONS.RESUBMIT_TASK,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_RUNS,
    PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.MANAGE_PEST_CONTROL,
    PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.MANAGE_GARBAGE,
    PERMISSIONS.VIEW_MACHINES
  ],

  RAILWAY_WORKER: [
    PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.SUBMIT_COACH_FORM,
    PERMISSIONS.VIEW_TASKS, PERMISSIONS.SUBMIT_TASKS,
    PERMISSIONS.START_TASK, PERMISSIONS.COMPLETE_TASK, PERMISSIONS.RESUBMIT_TASK,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_RUNS,
    PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.MANAGE_PEST_CONTROL,
    PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.MANAGE_GARBAGE,
    PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.VIEW_INSPECTIONS, PERMISSIONS.SCORE_INSPECTION
  ],

  JANITOR: [
    PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.SUBMIT_COACH_FORM,
    PERMISSIONS.VIEW_TASKS, PERMISSIONS.SUBMIT_TASKS,
    PERMISSIONS.START_TASK, PERMISSIONS.COMPLETE_TASK, PERMISSIONS.RESUBMIT_TASK,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_RUNS,
    PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.MANAGE_PEST_CONTROL,
    PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.MANAGE_GARBAGE,
    PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.VIEW_INSPECTIONS, PERMISSIONS.SCORE_INSPECTION
  ],

  ATTENDANT: [
    PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.SUBMIT_COACH_FORM,
    PERMISSIONS.VIEW_TASKS, PERMISSIONS.SUBMIT_TASKS,
    PERMISSIONS.START_TASK, PERMISSIONS.COMPLETE_TASK, PERMISSIONS.RESUBMIT_TASK,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_RUNS,
    PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.MANAGE_PEST_CONTROL,
    PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.MANAGE_GARBAGE,
    PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.VIEW_INSPECTIONS, PERMISSIONS.SCORE_INSPECTION
  ]
});
