import { db, admin } from '../database/index.js';
import { ReportService as ReportServiceLegacy } from '../../report_service.js';
import { PDFRenderer } from '../../pdf_renderer.js';
import { ExcelGenerator } from '../../excel_generator.js';
import { createWorkbook, addSummarySheet, addDataSheet, createPdf, drawPdfHeader, drawPdfSection, drawPdfTable } from '../reports/reportHelper.js';
import { NotFoundError, ValidationError, ForbiddenError } from '../errors/index.js';
import config from '../config/index.js';
import logger from '../logger/index.js';
import PDFDocument from 'pdfkit';
import path from 'path';
import fs from 'fs';

class ReportService {
  constructor() {
    this.legacyService = new ReportServiceLegacy(db);
  }

  async logAudit(action, params) {
    const {
      userId, userName, userRole, trainNumber, details
    } = params;
    await db.collection('audit_evidence').add({
      action,
      userId: userId || null,
      userName: userName || 'System',
      userRole: userRole || null,
      trainNumber: trainNumber || null,
      details: details || null,
      timestamp: admin.firestore.FieldValue.serverTimestamp()
    });
  }

  async generatePDFReport(reportData) {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];

    return new Promise((resolve, reject) => {
      doc.on('data', chunk => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const {
        title, generatedBy, trainNumber, coach, contractor,
        periodStart, periodEnd, sections = [], images = []
      } = reportData;

      doc.fontSize(18).font('Helvetica-Bold').text('INDIAN RAILWAYS', { align: 'center' });
      doc.fontSize(14).text('Coach & Washroom Cleaning System', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica-Bold').text(title || 'EVIDENCE REPORT', { align: 'center' });
      doc.moveDown();

      doc.fontSize(9).font('Helvetica');
      const metaLines = [
        `Generated By: ${generatedBy || 'System'}`,
        `Period: ${periodStart || 'N/A'} to ${periodEnd || 'N/A'}`
      ];
      if (trainNumber) metaLines.push(`Train: ${trainNumber}`);
      if (coach) metaLines.push(`Coach: ${coach}`);
      if (contractor) metaLines.push(`Contractor: ${contractor}`);

      metaLines.forEach(line => doc.text(line, { align: 'left' }));
      doc.moveDown();

      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
      doc.moveDown();

      for (const section of sections) {
        if (doc.y > 700) doc.addPage();

        doc.fontSize(11).font('Helvetica-Bold').text(section.heading, { underline: true });
        doc.moveDown(0.3);

        if (section.items && section.items.length > 0) {
          const colWidths = section.colWidths || [80, 120, 120, 80, 80];
          const headers = section.headers || ['Field', 'Value'];
          const startX = 50;
          let y = doc.y;

          doc.fontSize(8).font('Helvetica-Bold');
          let x = startX;
          headers.forEach((h, i) => {
            doc.text(h, x, y, { width: colWidths[i], align: 'left' });
            x += colWidths[i];
          });
          doc.moveDown(0.5);
          y = doc.y;
          doc.moveTo(50, y - 2).lineTo(545, y - 2).stroke('#dddddd');

          doc.fontSize(8).font('Helvetica');
          for (const item of section.items) {
            if (doc.y > 720) doc.addPage();
            y = doc.y;
            x = startX;
            const values = section.fields ? section.fields.map(f => item[f] || '') : [item.label || '', item.value || ''];
            values.forEach((v, i) => {
              doc.text(String(v), x, y, { width: colWidths[i], align: 'left' });
              x += colWidths[i];
            });
            doc.moveDown(0.4);
          }
        } else {
          doc.fontSize(9).font('Helvetica').text('No data available', { indent: 20 });
        }
        doc.moveDown();
      }

      if (images.length > 0) {
        if (doc.y > 650) doc.addPage();
        doc.fontSize(11).font('Helvetica-Bold').text('EVIDENCE IMAGES', { underline: true });
        doc.moveDown();

        for (const img of images) {
          if (doc.y > 700) doc.addPage();
          try {
            if (img.path && fs.existsSync(img.path)) {
              const imgWidth = Math.min(250, img.width || 200);
              doc.image(img.path, 50, doc.y, { width: imgWidth });
              doc.moveDown(4);
              doc.fontSize(8).font('Helvetica').text(`${img.caption || ''}`, { indent: 50 });
              doc.moveDown(0.5);
            } else if (img.url) {
              doc.fontSize(8).font('Helvetica').text(`[Image: ${img.caption || img.url}]`, { indent: 20 });
              doc.moveDown(0.3);
            }
          } catch {
            doc.fontSize(8).font('Helvetica').text(`[Image unavailable: ${img.caption || 'unknown'}]`, { indent: 20 });
            doc.moveDown(0.3);
          }
        }
      }

      const footerY = doc.page.height - 50;
      doc.fontSize(7).font('Helvetica').text(
        `Generated on ${new Date().toLocaleString()} | Railway Evidence Management System`,
        50, footerY, { align: 'center', width: 495 }
      );

      doc.end();
    });
  }

  async getPremisesData(user, query) {
    const { zone, division, depot, startDate, endDate, areaType, contractorId, contractId, supervisorId } = query;
    if (contractId) {
      const contractDoc = await db.collection('contracts').doc(contractId).get();
      if (!contractDoc.exists) throw new NotFoundError('Contract Not Found');
      const cData = contractDoc.data();
      const isStatusExpired = ['Expired', 'expired', 'Inactive', 'inactive'].includes(cData.status);
      let isDateExpired = false;
      if (cData.endDate) { const today = new Date(); const end = new Date(cData.endDate); end.setHours(23, 59, 59, 999); if (today > end) isDateExpired = true; }
      if (isStatusExpired || isDateExpired) throw new ValidationError('Contract Expired', `Expired on ${cData.endDate || 'Unknown'}`);
    }
    let queryRef = db.collection('premisesForms').where('status', 'in', ['LOCKED', 'AUTO-APPROVED']);
    if (zone) queryRef = queryRef.where('submittedByZone', '==', zone);
    if (division) queryRef = queryRef.where('submittedByDivision', '==', division);
    if (depot) queryRef = queryRef.where('submittedByDepot', '==', depot);
    if (contractorId) queryRef = queryRef.where('submittedByEntityId', '==', contractorId);
    if (contractId) queryRef = queryRef.where('contractId', '==', contractId);
    if (supervisorId) queryRef = queryRef.where('submittedById', '==', supervisorId);
    const snapshot = await queryRef.limit(200).get();
    let reportData = [];
    const start = startDate ? new Date(startDate) : null;
    const end = endDate ? new Date(endDate) : null;
    if (end) end.setHours(23, 59, 59, 999);
    const selectedAreas = areaType ? areaType.split(',').map(item => item.trim()) : [];
    const areaMap = { 'GICC': 23530, 'OWS': 8630, 'NWS': 10130 };
    snapshot.forEach(doc => {
      const data = doc.data();
      const formDate = data.formDateTime ? new Date(data.formDateTime) : new Date();
      let includeRecord = true;
      if (start && formDate < start) includeRecord = false;
      if (end && formDate > end) includeRecord = false;
      if (includeRecord && selectedAreas.length > 0 && !selectedAreas.includes(data.location)) includeRecord = false;
      if (includeRecord) {
        const summary = data.ratingDetails?.summary || {};
        const totalAreaSqMtr = data.area || areaMap[data.location] || 0;
        const overallPct = parseFloat(summary.overallAveragePct) || 0;
        let pen8190 = 'NA', pen7180 = 'NA', pen70 = 'NA';
        if (overallPct >= 81 && overallPct <= 90) pen8190 = 'Yes';
        else if (overallPct >= 71 && overallPct <= 80) pen7180 = 'Yes';
        else if (overallPct <= 70) pen70 = 'Yes';
        reportData.push({
          date: formDate.toLocaleDateString('en-IN'),
          premiseName: data.location || 'Unknown',
          location: data.location || 'Unknown',
          areaCategory: totalAreaSqMtr,
          totalArea: totalAreaSqMtr,
          areaAttended: totalAreaSqMtr,
          areaNotAttended: 0,
          ratingInPct: overallPct.toFixed(2) + '%',
          housekeepingScore: summary.housekeepingAveragePct || '0%',
          pitLineScore: summary.pitLineAveragePct || '0%',
          garbageScore: summary.garbageDisposalAveragePct || '0%',
          overallScore: summary.overallAveragePct || '0%',
          above90: overallPct > 90 ? 'Yes' : 'NA',
          penalty81to90: pen8190,
          penalty71to80: pen7180,
          penaltyBelow70: pen70
        });
      }
    });
    return { count: reportData.length, data: reportData };
  }

  async getCoachData(user, query) {
    const { zone, division, depot, startDate, endDate, contractorId, contractId, trainNo, coachNo, supervisorId, areaType } = query;
    if (contractId) {
      const contractDoc = await db.collection('contracts').doc(contractId).get();
      if (!contractDoc.exists) throw new NotFoundError('Contract Not Found');
      const cData = contractDoc.data();
      const isStatusExpired = ['Expired', 'expired', 'Inactive', 'inactive'].includes(cData.status);
      let isDateExpired = false;
      if (cData.endDate) { const today = new Date(); const end = new Date(cData.endDate); end.setHours(23, 59, 59, 999); if (today > end) isDateExpired = true; }
      if (isStatusExpired || isDateExpired) throw new ValidationError('Contract Expired', `Expired on ${cData.endDate || 'Unknown'}`);
    }
    let queryRef = db.collection('coachForms').where('status', 'in', ['LOCKED', 'AUTO-APPROVED']);
    if (zone) queryRef = queryRef.where('submittedByZone', '==', zone);
    if (division) queryRef = queryRef.where('submittedByDivision', '==', division);
    if (depot) queryRef = queryRef.where('submittedByDepot', '==', depot);
    if (contractorId) queryRef = queryRef.where('submittedByEntityId', '==', contractorId);
    if (contractId) queryRef = queryRef.where('contractId', '==', contractId);
    if (supervisorId) queryRef = queryRef.where('submittedById', '==', supervisorId);
    const snapshot = await queryRef.limit(200).get();
    let reportData = [];
    const start = startDate ? new Date(startDate) : null;
    const end = endDate ? new Date(endDate) : null;
    if (end) end.setHours(23, 59, 59, 999);
    const selectedAreas = areaType ? areaType.split(',').map(item => item.trim()) : [];
    snapshot.forEach(doc => {
      const data = doc.data();
      const formDate = data.formDateTime ? new Date(data.formDateTime) : new Date();
      let includeRecord = true;
      if (start && formDate < start) includeRecord = false;
      if (end && formDate > end) includeRecord = false;
      if (selectedAreas.length > 0 && !selectedAreas.includes(data.location)) includeRecord = false;
      if (includeRecord && trainNo) { if (!String(data.trainNumber || '').includes(trainNo)) includeRecord = false; }
      if (includeRecord && coachNo) {
        const coaches = data.ratingDetails?.coachEvaluationTable || [];
        if (!coaches.some(c => c.coachNumber && c.coachNumber.includes(coachNo))) includeRecord = false;
      }
      if (includeRecord) {
        const evalTable = data.ratingDetails?.coachEvaluationTable || [];
        const totalCoaches = evalTable.length;
        const workType = (data.ratingDetails?.workType || 'N/A').toLowerCase();
        const acwpStatus = (data.ratingDetails?.acwpStatus || 'Without ACWP').toLowerCase();
        const machinesList = data.machinesUsed || [];
        const isMachineUsed = machinesList.length > 0;
        let counts = {
          internal: { A: 0, B: 0, C: 0, D: 0, NA: 0 },
          rbpcMachine: { A: 0, B: 0, C: 0, D: 0, NA: 0 },
          rbpcManual: { A: 0, B: 0, C: 0, D: 0, NA: 0 },
          extAcwp: { A: 0, B: 0, C: 0, D: 0, NA: 0 },
          extManual: { A: 0, B: 0, C: 0, D: 0, NA: 0 },
          intensive: { A: 0, B: 0, C: 0, D: 0, NA: 0 },
          toiletries: { Yes: 0, No: 0, NA: 0 },
          watering: { Yes: 0, No: 0, NA: 0 },
          doors: { Yes: 0, No: 0, NA: 0 }
        };
        const inc = (obj, key) => { if (key && obj[key] !== undefined) obj[key]++; };
        evalTable.forEach(coach => {
          inc(counts.internal, coach.internalCleaning);
          inc(counts.intensive, coach.intensiveCleaning);
          inc(counts.toiletries, coach.toiletries);
          inc(counts.watering, coach.watering);
          inc(counts.doors, coach.doorsLocking);
          if (workType.includes('rbpc')) {
            if (isMachineUsed) inc(counts.rbpcMachine, coach.externalCleaning);
            else inc(counts.rbpcManual, coach.externalCleaning);
          } else {
            if (acwpStatus.includes('with acwp') || acwpStatus === 'functional') inc(counts.extAcwp, coach.externalCleaning);
            else inc(counts.extManual, coach.externalCleaning);
          }
        });
        let requiredManpower = 0;
        const isPrimSec = workType.includes('primary') || workType.includes('secondary');
        const isRBPC = workType.includes('rbpc');
        const hasACWP = acwpStatus.includes('with acwp') || acwpStatus === 'functional';
        if (isPrimSec) {
          requiredManpower += (totalCoaches * 0.45);
          requiredManpower += hasACWP ? (totalCoaches * 0.05) : (totalCoaches * 0.2);
        }
        if (isRBPC) requiredManpower += (totalCoaches * 0.3);
        const calculatedReq = Math.ceil(requiredManpower);
        const actualProvided = data.manpower ? data.manpower.length : 0;
        const shortage = Math.max(0, calculatedReq - actualProvided);
        const fmt = (val) => (val === 0 ? '' : val);
        reportData.push({
          date: formDate.toLocaleDateString('en-IN'),
          trainName: data.trainName || 'N/A',
          trainNo: data.trainNumber || 'N/A',
          workType: data.ratingDetails?.workType,
          acwpStatus: data.ratingDetails?.acwpStatus,
          int_A: fmt(counts.internal.A), int_B: fmt(counts.internal.B), int_C: fmt(counts.internal.C), int_D: fmt(counts.internal.D), int_NA: fmt(counts.internal.NA),
          rbpc_mach_A: fmt(counts.rbpcMachine.A), rbpc_mach_B: fmt(counts.rbpcMachine.B), rbpc_mach_C: fmt(counts.rbpcMachine.C), rbpc_mach_D: fmt(counts.rbpcMachine.D), rbpc_mach_NA: fmt(counts.rbpcMachine.NA),
          rbpc_man_A: fmt(counts.rbpcManual.A), rbpc_man_B: fmt(counts.rbpcManual.B), rbpc_man_C: fmt(counts.rbpcManual.C), rbpc_man_D: fmt(counts.rbpcManual.D), rbpc_man_NA: fmt(counts.rbpcManual.NA),
          ext_acwp_A: fmt(counts.extAcwp.A), ext_acwp_B: fmt(counts.extAcwp.B), ext_acwp_C: fmt(counts.extAcwp.C), ext_acwp_D: fmt(counts.extAcwp.D), ext_acwp_NA: fmt(counts.extAcwp.NA),
          ext_man_A: fmt(counts.extManual.A), ext_man_B: fmt(counts.extManual.B), ext_man_C: fmt(counts.extManual.C), ext_man_D: fmt(counts.extManual.D), ext_man_NA: fmt(counts.extManual.NA),
          intense_A: fmt(counts.intensive.A), intense_B: fmt(counts.intensive.B), intense_C: fmt(counts.intensive.C), intense_D: fmt(counts.intensive.D), intense_NA: fmt(counts.intensive.NA),
          toil_Yes: fmt(counts.toiletries.Yes), toil_No: fmt(counts.toiletries.No), toil_NA: fmt(counts.toiletries.NA),
          water_Yes: fmt(counts.watering.Yes), water_No: fmt(counts.watering.No), water_NA: fmt(counts.watering.NA),
          door_Yes: fmt(counts.doors.Yes), door_No: fmt(counts.doors.No), door_NA: fmt(counts.doors.NA),
          actualWithACWP: hasACWP ? actualProvided : 'N/A',
          actualWithoutACWP: !hasACWP ? actualProvided : 'N/A',
          manpowerShortage: shortage > 0 ? shortage : 'Nil',
          machineShortage: 'N/A'
        });
      }
    });
    return { count: reportData.length, data: reportData };
  }

  async getTrainPerformance(user, query) {
    const { uid, role, userType, zone, division, depot, entityId } = user;
    const { trainNo, startDate, endDate } = query;
    let queryRef = db.collection('coachForms').where('status', 'in', ['LOCKED', 'AUTO-APPROVED']);
    const userRole = (role || "").toLowerCase().replace(/_/g, " ");
    const isMaster = userRole.includes('master') || userRole === 'company master';
    const isAdmin = (!userRole.includes("super admin") && userRole.includes("admin")) || userRole === 'company admin';
    if (userType === 'railway') {
      if (isMaster) { if (zone) queryRef = queryRef.where('submittedByZone', '==', zone); }
      else if (isAdmin) queryRef = queryRef.where('submittedByDivision', '==', division);
      else queryRef = queryRef.where('submittedTo.railwayEmployeeId', '==', uid);
    } else if (userType === 'contractor') {
      if (!entityId) throw new ForbiddenError('Entity ID missing.');
      queryRef = queryRef.where('submittedByEntityId', '==', entityId);
      if (isMaster) { /* all company data */ }
      else if (isAdmin) queryRef = queryRef.where('submittedByDivision', '==', division);
      else queryRef = queryRef.where('submittedById', '==', uid);
    }
    const snapshot = await queryRef.limit(200).get();
    const trainStats = {};
    const start = startDate ? new Date(startDate) : null;
    const end = endDate ? new Date(endDate) : null;
    if (end) end.setHours(23, 59, 59, 999);
    snapshot.forEach(doc => {
      const data = doc.data(); const formDate = new Date(data.formDateTime);
      let include = true;
      if (start && formDate < start) include = false;
      if (end && formDate > end) include = false;
      const tName = data.trainName || 'Unknown Train';
      if (trainNo && !tName.includes(trainNo)) include = false;
      if (include) {
        if (!trainStats[tName]) trainStats[tName] = { trainName: tName, totalForms: 0, totalScore: 0, scoresList: [] };
        const score = parseFloat(data.ratingDetails?.summary?.overallAveragePct || '0');
        trainStats[tName].totalForms++; trainStats[tName].totalScore += score;
        trainStats[tName].scoresList.push({ date: formDate.toLocaleDateString('en-IN'), score: score.toFixed(2), contractor: data.submittedByEntityName, supervisor: data.submittedByName, location: data.submittedByDepot });
      }
    });
    const finalResult = Object.values(trainStats).map(train => ({ trainName: train.trainName, formsCount: train.totalForms, averageScore: (train.totalScore / train.totalForms).toFixed(2) + '%', details: train.scoresList }));
    return { count: finalResult.length, data: finalResult };
  }

  async getCoachStats(user, query) {
    const { uid, role, userType, entityId, division } = user;
    const { startDate, endDate, contractId } = query;
    let queryRef = db.collection('coachForms').where('status', 'in', ['LOCKED', 'AUTO-APPROVED']);
    const userRole = (role || "").toLowerCase().replace(/_/g, " ");
    const isMaster = userRole.includes('master');
    const isAdmin = (!userRole.includes("super admin") && userRole.includes("admin"));
    if (userType === 'contractor') {
      if (!entityId) throw new ForbiddenError('Entity ID missing.');
      queryRef = queryRef.where('submittedByEntityId', '==', entityId);
      if (!isMaster && isAdmin) queryRef = queryRef.where('submittedByDivision', '==', division);
      else if (!isMaster && !isAdmin) queryRef = queryRef.where('submittedById', '==', uid);
    } else { if (isAdmin) queryRef = queryRef.where('submittedByDivision', '==', division); }
    if (contractId) queryRef = queryRef.where('contractId', '==', contractId);
    const snapshot = await queryRef.limit(200).get();
    let stats = { totalTrains: 0, totalCoaches: 0, totalManpower: 0, totalPenalty: 0, grades: { A: 0, B: 0, C: 0, D: 0 }, operations: { toiletries: { Yes: 0, No: 0, NA: 0 }, doors: { Yes: 0, No: 0, NA: 0 }, watering: { Yes: 0, No: 0, NA: 0 } }, resources: { manpowerDeployed: 0, machinesUsed: 0 } };
    const start = startDate ? new Date(startDate) : null;
    const end = endDate ? new Date(endDate) : null;
    if (end) end.setHours(23, 59, 59, 999);
    snapshot.forEach(doc => {
      const data = doc.data();
      let include = true;
      if (start || end) { if (!data.formDateTime) include = false; else { const fDate = new Date(data.formDateTime); if (start && fDate < start) include = false; if (end && fDate > end) include = false; } }
      if (include) {
        stats.totalTrains++;
        const mpCount = data.manpower ? data.manpower.length : 0;
        stats.totalManpower += mpCount; stats.resources.manpowerDeployed += mpCount;
        stats.resources.machinesUsed += (data.machinesUsed || []).length;
        const summary = data.ratingDetails?.summary || {};
        stats.totalCoaches += (summary.totalCoaches || 0);
        ['internal', 'external', 'intensive'].forEach(cat => { if (summary[cat]) { stats.grades.A += (summary[cat].A || 0); stats.grades.B += (summary[cat].B || 0); stats.grades.C += (summary[cat].C || 0); stats.grades.D += (summary[cat].D || 0); } });
        const addOpStats = (target, source) => { if (!source) return; target.Yes += (source.Yes || 0); target.No += (source.No || 0); target.NA += (source.NA || 0); };
        addOpStats(stats.operations.doors, summary.doorsLocking);
        addOpStats(stats.operations.toiletries, summary.toiletries);
        addOpStats(stats.operations.watering, summary.watering);
      }
    });
    const totalGrades = stats.grades.A + stats.grades.B + stats.grades.C + stats.grades.D || 1;
    return {
      cards: { totalTrains: stats.totalTrains, totalCoaches: stats.totalCoaches, totalManpower: stats.totalManpower, totalPenalty: stats.totalPenalty },
      gradeDistribution: { A: { count: stats.grades.A, pct: ((stats.grades.A / totalGrades) * 100).toFixed(1) }, B: { count: stats.grades.B, pct: ((stats.grades.B / totalGrades) * 100).toFixed(1) }, C: { count: stats.grades.C, pct: ((stats.grades.C / totalGrades) * 100).toFixed(1) }, D: { count: stats.grades.D, pct: ((stats.grades.D / totalGrades) * 100).toFixed(1) } },
      operations: { toiletries: stats.operations.toiletries, doors: stats.operations.doors, watering: stats.operations.watering },
      resources: stats.resources
    };
  }

  async getPremisesStats(user, query) {
    const { uid, role, userType, entityId, division } = user;
    const { startDate, endDate, contractId } = query;
    let queryRef = db.collection('premisesForms').where('status', 'in', ['LOCKED', 'AUTO-APPROVED']);
    const userRole = (role || "").toLowerCase().replace(/_/g, " ");
    const isMaster = userRole.includes('master');
    const isAdmin = (!userRole.includes("super admin") && userRole.includes("admin"));
    if (userType === 'contractor') {
      if (!entityId) throw new ForbiddenError('Entity ID missing.');
      queryRef = queryRef.where('submittedByEntityId', '==', entityId);
      if (!isMaster && isAdmin) queryRef = queryRef.where('submittedByDivision', '==', division);
      else if (!isMaster && !isAdmin) queryRef = queryRef.where('submittedById', '==', uid);
    } else { if (isAdmin) queryRef = queryRef.where('submittedByDivision', '==', division); }
    if (contractId) queryRef = queryRef.where('contractId', '==', contractId);
    const snapshot = await queryRef.limit(200).get();
    let stats = { totalForms: 0, totalAreaCleaned: 0, totalManpower: 0, quality: { above90: 0, range81to90: 0, range71to80: 0, below70: 0 }, uniqueDates: new Set() };
    const areaMap = { 'GICC': 23530, 'OWS': 8630, 'NWS': 10130 };
    const start = startDate ? new Date(startDate) : null;
    const end = endDate ? new Date(endDate) : null;
    if (end) end.setHours(23, 59, 59, 999);
    snapshot.forEach(doc => {
      const data = doc.data();
      let include = true;
      if (start || end) { if (!data.formDateTime) include = false; else { const fDate = new Date(data.formDateTime); if (start && fDate < start) include = false; if (end && fDate > end) include = false; } }
      if (include) {
        stats.totalForms++;
        stats.totalAreaCleaned += parseFloat(data.area) || areaMap[data.location] || 0;
        stats.totalManpower += data.manpower ? data.manpower.length : 0;
        if (data.formDateTime) stats.uniqueDates.add(new Date(data.formDateTime).toDateString());
        const pct = parseFloat(data.ratingDetails?.summary?.overallAveragePct || 0);
        if (pct > 90) stats.quality.above90++;
        else if (pct >= 81) stats.quality.range81to90++;
        else if (pct >= 71) stats.quality.range71to80++;
        else stats.quality.below70++;
      }
    });
    return stats;
  }

  async getCtsStats(user, query) {
    const { uid, role, userType, entityId, division } = user;
    const { startDate, endDate, contractId } = query;
    let queryRef = db.collection('ctsForms').where('status', 'in', ['LOCKED', 'AUTO-APPROVED']);
    const userRole = (role || "").toLowerCase().replace(/_/g, " ");
    const isMaster = userRole.includes('master');
    const isAdmin = (!userRole.includes("super admin") && userRole.includes("admin"));
    if (userType === 'contractor') {
      if (!entityId) throw new ForbiddenError('Entity ID missing.');
      queryRef = queryRef.where('submittedByEntityId', '==', entityId);
      if (!isMaster && isAdmin) queryRef = queryRef.where('submittedByDivision', '==', division);
      else if (!isMaster && !isAdmin) queryRef = queryRef.where('submittedById', '==', uid);
    } else { if (isAdmin) queryRef = queryRef.where('submittedByDivision', '==', division); }
    if (contractId) queryRef = queryRef.where('contractId', '==', contractId);
    const snapshot = await queryRef.limit(200).get();
    let stats = {
      totalTrains: 0, totalCoachesCleaned: 0, totalUnattendedCoaches: 0,
      totalSampledCoaches: 0, sumSamplingPercentage: 0, windowTimeCount: 0, sumWindowTime: 0,
      grades: { A: 0, B: 0, C: 0, D: 0 },
      ops: { toiletOccupied: 0, toiletUnattended: 0, totalScoreSum: 0, scoredFormsCount: 0 },
      resources: { manpowerTotal: 0, chemicalQuantity: 0, machinesUsed: 0 }
    };
    const start = startDate ? new Date(startDate) : null;
    const end = endDate ? new Date(endDate) : null;
    if (end) end.setHours(23, 59, 59, 999);
    snapshot.forEach(doc => {
      const data = doc.data();
      let include = true;
      if (start || end) { if (!data.formDateTime) include = false; else { const fDate = new Date(data.formDateTime); if (start && fDate < start) include = false; if (end && fDate > end) include = false; } }
      if (include) {
        stats.totalTrains++;
        const attended = Number(data.coachesAttended) || 0;
        const inRake = Number(data.coachesInRake) || 0;
        stats.totalCoachesCleaned += attended;
        stats.totalUnattendedCoaches += (inRake - attended);
        if (data.allowedWindow) { stats.sumWindowTime += Number(data.allowedWindow); stats.windowTimeCount++; }
        stats.resources.manpowerTotal += (data.attendanceStaff ? data.attendanceStaff.length : 0);
        const rating = data.ratingDetails || {};
        const chemicalsArray = rating.chemicals || [];
        chemicalsArray.forEach(c => { stats.resources.chemicalQuantity += (parseFloat(c.quantity) || 0); });
        const summary = rating.summary || {};
        if (summary.overallGrade) {
          const g = summary.overallGrade;
          if (g.includes('(A)')) stats.grades.A++;
          else if (g.includes('(B)')) stats.grades.B++;
          else if (g.includes('(C)')) stats.grades.C++;
          else stats.grades.D++;
          stats.ops.totalScoreSum += (Number(summary.averageScore) || 0);
          stats.ops.scoredFormsCount++;
        }
        const evalTable = rating.coachEvaluationTable || [];
        stats.totalSampledCoaches += evalTable.length;
        if (rating.inspectionHeader) { stats.sumSamplingPercentage += (Number(rating.inspectionHeader.samplingPercentage) || 0); }
        stats.ops.toiletOccupied += (Number(data.occupiedToilets) || 0);
        stats.ops.toiletUnattended += (Number(data.occupiedToilets) || 0);
        if (Array.isArray(rating.machinesUsed)) { stats.resources.machinesUsed += rating.machinesUsed.length; }
      }
    });
    const totalGrades = stats.grades.A + stats.grades.B + stats.grades.C + stats.grades.D || 1;
    const avgScore = stats.ops.scoredFormsCount > 0 ? (stats.ops.totalScoreSum / stats.ops.scoredFormsCount).toFixed(2) : 0;
    const avgWindow = stats.windowTimeCount > 0 ? (stats.sumWindowTime / stats.windowTimeCount).toFixed(0) : 0;
    const avgSamplingPct = stats.totalTrains > 0 ? (stats.sumSamplingPercentage / stats.totalTrains).toFixed(1) : 0;
    return {
      statistics: {
        totalTrains: stats.totalTrains, totalCoachesCleaned: stats.totalCoachesCleaned,
        totalUnattendedCoaches: stats.totalUnattendedCoaches, sampledCoaches: stats.totalSampledCoaches,
        samplingPercentage: `${avgSamplingPct}%`, averageWindowTime: `${avgWindow} Min`
      },
      gradeDistribution: {
        A: { count: stats.grades.A, pct: ((stats.grades.A / totalGrades) * 100).toFixed(1) },
        B: { count: stats.grades.B, pct: ((stats.grades.B / totalGrades) * 100).toFixed(1) },
        C: { count: stats.grades.C, pct: ((stats.grades.C / totalGrades) * 100).toFixed(1) },
        D: { count: stats.grades.D, pct: ((stats.grades.D / totalGrades) * 100).toFixed(1) }
      },
      cleaningOperations: { toiletOccupied: stats.ops.toiletOccupied, averageScore: avgScore, toiletUnattended: stats.ops.toiletUnattended },
      resourcesUsed: { manpowerTotal: stats.resources.manpowerTotal, chemicalQuantity: stats.resources.chemicalQuantity.toFixed(1), machineryUsed: stats.resources.machinesUsed }
    };
  }

  async getCtsData(user, query) {
    const { zone, division, depot, startDate, endDate, contractorId, contractId, supervisorId } = query;
    let queryRef = db.collection('ctsForms').where('status', 'in', ['LOCKED', 'AUTO-APPROVED']);
    if (zone) queryRef = queryRef.where('submittedByZone', '==', zone);
    if (division) queryRef = queryRef.where('submittedByDivision', '==', division);
    if (depot) queryRef = queryRef.where('submittedByDepot', '==', depot);
    if (contractorId) queryRef = queryRef.where('submittedByEntityId', '==', contractorId);
    if (contractId) queryRef = queryRef.where('contractId', '==', contractId);
    if (supervisorId) queryRef = queryRef.where('submittedById', '==', supervisorId);
    const snapshot = await queryRef.limit(200).get();
    let reportData = [];
    const start = startDate ? new Date(startDate) : null;
    const end = endDate ? new Date(endDate) : null;
    if (end) end.setHours(23, 59, 59, 999);
    snapshot.forEach(doc => {
      const data = doc.data();
      const formDate = data.formDateTime ? new Date(data.formDateTime) : new Date();
      let include = true;
      if (start && formDate < start) include = false;
      if (end && formDate > end) include = false;
      if (include) { reportData.push({ date: formDate.toLocaleDateString('en-IN'), trainName: data.trainName || 'N/A', trainNo: data.trainNumber || 'N/A', submittedBy: data.submittedByName, averageScore: data.ratingDetails?.summary?.averageScore || 'N/A', overallGrade: data.ratingDetails?.summary?.overallGrade || 'N/A' }); }
    });
    return { count: reportData.length, data: reportData };
  }

  async generateReport(user, body) {
    const reportData = {
      title: body.title || 'EVIDENCE REPORT',
      generatedBy: user.fullName || user.name,
      trainNumber: body.trainNumber,
      coach: body.coach,
      contractor: body.contractor,
      periodStart: body.periodStart,
      periodEnd: body.periodEnd,
      sections: body.sections || [],
      images: body.images || []
    };

    const pdfBuffer = await this.generatePDFReport(reportData);

    const reportRef = db.collection('report_history').doc();
    await reportRef.set({
      reportId: reportRef.id,
      title: reportData.title,
      type: body.reportType || 'custom',
      generatedBy: user.uid,
      generatedByName: user.fullName,
      generatedByRole: user.role,
      trainNumber: reportData.trainNumber || null,
      coach: reportData.coach || null,
      contractor: reportData.contractor || null,
      periodStart: reportData.periodStart || null,
      periodEnd: reportData.periodEnd || null,
      fileSize: pdfBuffer.length,
      generatedAt: admin.firestore.FieldValue.serverTimestamp()
    });

    await this.logAudit('REPORT_GENERATED', {
      userId: user.uid, userName: user.fullName,
      userRole: user.role, trainNumber: reportData.trainNumber,
      details: `Generated report: ${reportData.title}`
    });

    return { pdfBuffer, filename: `${reportData.title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf` };
  }

  async emailReport(user, body) {
    const {
      reportType, subject, bodyHtml, sections, images,
      periodStart, periodEnd, trainNumber, coach, contractor,
      to, cc, bcc
    } = body;

    let sgMail;
    try {
      sgMail = (await import('@sendgrid/mail')).default;
      if (config.sendgrid.apiKey) {
        sgMail.setApiKey(config.sendgrid.apiKey);
      }
    } catch { /* sendgrid not available */ }

    const pdfBuffer = await this.generatePDFReport({
      title: subject || `${reportType} Report`,
      generatedBy: user.fullName,
      trainNumber, coach, contractor,
      periodStart, periodEnd,
      sections: sections || [],
      images: images || []
    });

    const recipients = to && to.length > 0
      ? to
      : [user.email || 'user@unknown.com'];

    const msg = {
      to: recipients,
      cc: cc || [],
      bcc: bcc || [],
      from: config.reporting.fromEmail || 'noreply@swachhrailways.com',
      subject: subject || `${(reportType || 'Report').toUpperCase()} Report - ${new Date().toISOString().split('T')[0]}`,
      html: bodyHtml || `<p>Please find attached the ${reportType} report.</p>`,
      attachments: [{
        content: pdfBuffer.toString('base64'),
        filename: `${reportType || 'report'}_${new Date().toISOString().split('T')[0]}.pdf`,
        type: 'application/pdf',
        disposition: 'attachment'
      }]
    };

    let sendResult = { messageId: 'simulated' };
    if (sgMail && config.sendgrid.apiKey) {
      try { sendResult = await sgMail.send(msg); } catch { /* fallback */ }
    }

    const emailRef = db.collection('email_history').doc();
    await emailRef.set({
      emailId: emailRef.id,
      reportType,
      subject: msg.subject,
      to: msg.to,
      cc: msg.cc,
      sentBy: user.uid,
      sentByName: user.fullName,
      sentByRole: user.role,
      pdfSize: pdfBuffer.length,
      sendgridMessageId: sendResult.messageId || sendResult[0]?.statusCode || 'simulated',
      sentAt: admin.firestore.FieldValue.serverTimestamp()
    });

    await this.logAudit('REPORT_EMAILED', {
      userId: user.uid, userName: user.fullName,
      userRole: user.role, trainNumber,
      details: `Emailed ${reportType} report to ${recipients.join(', ')}`
    });

    return {
      success: true,
      message: 'Report emailed successfully',
      emailId: emailRef.id,
      recipients,
      pdfSize: pdfBuffer.length
    };
  }

  async getReportHistory(filters = {}) {
    const { limit = 50, type, trainNumber } = filters;
    let query = db.collection('report_history').orderBy('generatedAt', 'desc').limit(parseInt(limit));
    if (type) query = query.where('type', '==', type);
    if (trainNumber) query = query.where('trainNumber', '==', trainNumber);
    const snap = await query.get();
    const reports = snap.docs.map(d => ({ id: d.id, ...d.data() }));
    return { success: true, count: reports.length, reports };
  }

  async getEmailHistory(filters = {}) {
    const { limit = 50 } = filters;
    const snap = await db.collection('email_history')
      .orderBy('sentAt', 'desc')
      .limit(parseInt(limit))
      .get();
    const emails = snap.docs.map(d => ({ id: d.id, ...d.data() }));
    return { success: true, count: emails.length, emails };
  }

  async generateAuditReport(user, body) {
    const { reportType, runInstanceId, workerId, format = 'pdf' } = body;
    if (!reportType || !runInstanceId) {
      throw new ValidationError('reportType and runInstanceId are required');
    }

    let data;
    let pdfBuffer;
    let excelBuffer;
    
    if (reportType === 'ATTENDANCE_AUDIT') {
      data = await this.legacyService.getAttendanceAuditData(runInstanceId, workerId);
    } else if (reportType === 'WORKER_ACTIVITY') {
      data = await this.legacyService.getAttendanceAuditData(runInstanceId, workerId);
    } else if (reportType === 'COMPLAINT_AUDIT') {
      data = await this.legacyService.getAttendanceAuditData(runInstanceId, workerId);
    } else if (reportType === 'OPERATIONAL_AUDIT') {
      data = await this.legacyService.getOperationalAuditData(runInstanceId);
    } else {
      throw new ValidationError('Invalid reportType');
    }

    if (format === 'excel') {
      const excelGen = new ExcelGenerator();
      excelGen.createSummarySheet(data, reportType.replace(/_/g, ' '));
      excelBuffer = await excelGen.getBuffer();
      return { data, excelBuffer, format };
    } else {
      const pdfRenderer = new PDFRenderer();
      if (reportType === 'ATTENDANCE_AUDIT') {
        pdfBuffer = await pdfRenderer.generateAttendanceAudit(data);
      } else if (reportType === 'WORKER_ACTIVITY_AUDIT') {
        pdfBuffer = await pdfRenderer.generateWorkerActivityAudit(data);
      } else if (reportType === 'COMPLAINT_AUDIT') {
        pdfBuffer = await pdfRenderer.generateComplaintAudit(data);
      } else if (reportType === 'OPERATIONAL_AUDIT') {
        pdfBuffer = await pdfRenderer.generateEnterpriseOperationalAudit(data);
      }
      return { data, pdfBuffer, format };
    }
  }

  async sendEmail(user, body) {
    const { reportType, runInstanceId, workerId, emailTo = user.email || 'hirenkodwani@gmail.com' } = body;

    if (!reportType || !runInstanceId) {
      throw new ValidationError('reportType and runInstanceId are required');
    }

    let data;
    if (reportType === 'ATTENDANCE_AUDIT') {
      data = await this.legacyService.getAttendanceAuditData(runInstanceId, workerId);
    } else if (reportType === 'OPERATIONAL_AUDIT') {
      data = await this.legacyService.getOperationalAuditData(runInstanceId);
    } else if (reportType === 'WORKER_ACTIVITY_AUDIT') {
      data = await this.legacyService.getWorkerActivityAuditData(runInstanceId, workerId);
    } else if (reportType === 'COMPLAINT_AUDIT') {
      data = await this.legacyService.getComplaintAuditData(runInstanceId);
    } else {
      data = await this.legacyService.getOperationalAuditData(runInstanceId);
    }

    const excelGen = new ExcelGenerator();
    excelGen.createSummarySheet(data, reportType.replace(/_/g, ' '));
    const excelBuffer = await excelGen.getBuffer();

    let pdfBuffer;
    const pdfRenderer = new PDFRenderer();
    if (reportType === 'ATTENDANCE_AUDIT') {
      pdfBuffer = await pdfRenderer.generateAttendanceAudit(data);
    } else if (reportType === 'WORKER_ACTIVITY_AUDIT') {
      pdfBuffer = await pdfRenderer.generateWorkerActivityAudit(data);
    } else if (reportType === 'COMPLAINT_AUDIT') {
      pdfBuffer = await pdfRenderer.generateComplaintAudit(data);
    } else {
      pdfBuffer = await pdfRenderer.generateEnterpriseOperationalAudit(data);
    }

    let emailResponse = { id: 'simulated' };
    try {
      const { autoEmailService } = await import('./autoEmailService.js');
      emailResponse = await autoEmailService._sendEmail({
        subject: `Compliance Report | ${data?.trainInfo?.['Train Name'] || ''} | ${data?.meta?.auditStatus || ''}`,
        to: emailTo,
        html: `
          <h2>Official Audit Report</h2>
          <p>Please find attached the latest <b>${reportType.replace(/_/g, ' ')}</b> for Run Instance ID: ${runInstanceId}.</p>
          <p><b>Status:</b> ${data?.kpi?.overallStatus || 'N/A'}</p>
          <br>
          <p>Generated by: ${user.fullName || 'System'}</p>
        `,
        attachments: [
          { filename: `${data?.meta?.reportId || 'report'}.pdf`, content: pdfBuffer, type: 'application/pdf' },
          { filename: `${data?.meta?.reportId || 'report'}.xlsx`, content: excelBuffer, type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }
        ]
      });
    } catch (e) {
      logger.warn('sendEmail', 'Email failed, using simulated send', e?.message);
    }

    return {
      success: true,
      message: 'Email sent successfully',
      emailResponse
    };
  }

  async generateDailyReport(user, body) {
    const { trainNumber, runInstanceId } = body;
    if (!trainNumber) throw new ValidationError('trainNumber required');

    const today = new Date().toISOString().split('T')[0];

    const tasksSnap = await db.collection('task_instances')
      .where('trainNumber', '==', trainNumber)
      .where('date', '==', today)
      .limit(200).get();

    const tasks = tasksSnap.docs.map(d => ({ id: d.id, ...d.data() }));
    const completed = tasks.filter(t => t.status === 'completed');
    const pending = tasks.filter(t => t.status === 'pending' || t.status === 'assigned');
    const escalated = tasks.filter(t => t.status === 'escalated');

    const complaintsSnap = await db.collection('complaints')
      .where('trainNumber', '==', trainNumber)
      .where('date', '==', today)
      .limit(200).get();
    const complaints = complaintsSnap.docs.map(d => ({ id: d.id, ...d.data() }));

    const evidenceSnap = await db.collection('evidence_metadata')
      .where('trainNumber', '==', trainNumber)
      .where('deleted', '==', false)
      .limit(200).get();
    const evidenceDocs = evidenceSnap.docs.map(d => d.data());

    const sections = [
      {
        heading: 'Task Summary',
        colWidths: [150, 80],
        headers: ['Metric', 'Count'],
        fields: ['label', 'value'],
        items: [
          { label: 'Tasks Generated', value: String(tasks.length) },
          { label: 'Tasks Completed', value: String(completed.length) },
          { label: 'Pending Tasks', value: String(pending.length) },
          { label: 'Escalations', value: String(escalated.length) }
        ]
      },
      {
        heading: 'Complaint Summary',
        colWidths: [150, 80],
        headers: ['Metric', 'Count'],
        fields: ['label', 'value'],
        items: [
          { label: 'Total Complaints', value: String(complaints.length) },
          { label: 'Images Uploaded', value: String(evidenceDocs.length) }
        ]
      },
      {
        heading: 'Evidence Summary',
        colWidths: [150, 80],
        headers: ['Evidence Type', 'Count'],
        fields: ['type', 'count'],
        items: Object.entries(
          evidenceDocs.reduce((acc, e) => {
            acc[e.evidenceType] = (acc[e.evidenceType] || 0) + 1;
            return acc;
          }, {})
        ).map(([type, count]) => ({ type, count: String(count) }))
      }
    ];

    const pdfBuffer = await this.generatePDFReport({
      title: `DAILY TRAIN REPORT - ${trainNumber}`,
      generatedBy: user.fullName,
      trainNumber,
      periodStart: today,
      periodEnd: today,
      sections
    });

    const reportRef = db.collection('report_history').doc();
    await reportRef.set({
      reportId: reportRef.id,
      title: `Daily Report - ${trainNumber}`,
      type: 'daily',
      generatedBy: user.uid,
      generatedByName: user.fullName,
      trainNumber,
      periodStart: today,
      periodEnd: today,
      summary: {
        totalTasks: tasks.length,
        completedTasks: completed.length,
        pendingTasks: pending.length,
        escalations: escalated.length,
        complaints: complaints.length,
        images: evidenceDocs.length
      },
      generatedAt: admin.firestore.FieldValue.serverTimestamp()
    });

    return { pdfBuffer, filename: `DAILY_${trainNumber}_${today}.pdf` };
  }

  async generateWeeklyReport(user, body) {
    const { contractor } = body;
    if (!contractor) throw new ValidationError('contractor required');

    const endDate = new Date();
    const startDate = new Date(endDate.getTime() - 7 * 86400000);
    const startStr = startDate.toISOString().split('T')[0];
    const endStr = endDate.toISOString().split('T')[0];

    const evidenceSnap = await db.collection('evidence_metadata')
      .where('contractor', '==', contractor)
      .where('deleted', '==', false)
      .limit(200).get();
    const evidenceDocs = evidenceSnap.docs.map(d => d.data());

    const complaintsSnap = await db.collection('complaints')
      .where('contractorId', '==', contractor)
      .limit(200).get();
    const complaints = complaintsSnap.docs.map(d => ({ id: d.id, ...d.data() }));

    const attendanceSnap = await db.collection('attendance_records')
      .where('contractorId', '==', contractor)
      .where('date', '>=', startStr)
      .where('date', '<=', endStr)
      .limit(200).get();
    const attendance = attendanceSnap.docs.map(d => ({ id: d.id, ...d.data() }));

    const presentCount = attendance.filter(a => a.status === 'present').length;
    const attendanceCompliance = attendance.length > 0
      ? ((presentCount / attendance.length) * 100).toFixed(1)
      : 'N/A';

    const tasksSnap = await db.collection('station_tasks')
      .where('contractorId', '==', contractor)
      .limit(200).get();
    const tasks = tasksSnap.docs.map(d => ({ id: d.id, ...d.data() }));
    const completedTasks = tasks.filter(t => t.status === 'completed');
    const completionPct = tasks.length > 0
      ? ((completedTasks.length / tasks.length) * 100).toFixed(1)
      : 'N/A';

    const sections = [
      {
        heading: 'Weekly Performance Summary',
        items: [
          { label: 'Contractor', value: contractor },
          { label: 'Period', value: `${startStr} to ${endStr}` },
          { label: 'Completion %', value: `${completionPct}%` },
          { label: 'Attendance Compliance', value: `${attendanceCompliance}%` },
          { label: 'Evidence Uploaded', value: String(evidenceDocs.length) },
          { label: 'Complaints', value: String(complaints.length) }
        ].map(i => ({ label: i.label, value: String(i.value) }))
      }
    ];

    const pdfBuffer = await this.generatePDFReport({
      title: 'WEEKLY CONTRACTOR REPORT',
      generatedBy: user.fullName,
      contractor,
      periodStart: startStr,
      periodEnd: endStr,
      sections
    });

    const reportRef = db.collection('report_history').doc();
    await reportRef.set({
      reportId: reportRef.id,
      title: `Weekly Report - ${contractor}`,
      type: 'weekly',
      generatedBy: user.uid,
      generatedByName: user.fullName,
      contractor,
      periodStart: startStr,
      periodEnd: endStr,
      summary: {
        completionPct,
        attendanceCompliance,
        evidenceCount: evidenceDocs.length,
        complaints: complaints.length
      },
      generatedAt: admin.firestore.FieldValue.serverTimestamp()
    });

    return { pdfBuffer, filename: `WEEKLY_${contractor}_${endStr}.pdf` };
  }

  async generateMonthlyReport(user, body) {
    const { division } = body;
    if (!division) throw new ValidationError('division required');

    const endDate = new Date();
    const startDate = new Date(endDate.getTime() - 30 * 86400000);
    const startStr = startDate.toISOString().split('T')[0];
    const endStr = endDate.toISOString().split('T')[0];

    const evidenceSnap = await db.collection('evidence_metadata')
      .where('division', '==', division)
      .where('deleted', '==', false)
      .limit(200).get();
    const evidenceDocs = evidenceSnap.docs.map(d => d.data());

    const contractorBreakdown = {};
    evidenceDocs.forEach(e => {
      const c = e.contractor || 'Unknown';
      if (!contractorBreakdown[c]) contractorBreakdown[c] = { evidenceCount: 0, totalBytes: 0 };
      contractorBreakdown[c].evidenceCount++;
      contractorBreakdown[c].totalBytes += e.compressedSize || e.originalSize || 0;
    });

    const trainBreakdown = {};
    evidenceDocs.forEach(e => {
      const t = e.trainNumber || 'Unknown';
      trainBreakdown[t] = (trainBreakdown[t] || 0) + 1;
    });

    const sections = [
      {
        heading: 'Evidence Summary',
        items: [
          { label: 'Total Evidence', value: String(evidenceDocs.length) },
          { label: 'Unique Trains', value: String(Object.keys(trainBreakdown).length) },
          { label: 'Unique Contractors', value: String(Object.keys(contractorBreakdown).length) }
        ]
      },
      {
        heading: 'Contractor Comparison',
        colWidths: [120, 80, 100],
        headers: ['Contractor', 'Evidence', 'Storage (MB)'],
        fields: ['name', 'evidence', 'storage'],
        items: Object.entries(contractorBreakdown).map(([name, data]) => ({
          name,
          evidence: String(data.evidenceCount),
          storage: (data.totalBytes / (1024 * 1024)).toFixed(2)
        }))
      },
      {
        heading: 'Train Evidence Count',
        colWidths: [120, 80],
        headers: ['Train', 'Images'],
        fields: ['train', 'count'],
        items: Object.entries(trainBreakdown)
          .sort((a, b) => b[1] - a[1])
          .slice(0, 20)
          .map(([train, count]) => ({ train, count: String(count) }))
      }
    ];

    const pdfBuffer = await this.generatePDFReport({
      title: 'MONTHLY DIVISION REPORT',
      generatedBy: user.fullName,
      periodStart: startStr,
      periodEnd: endStr,
      sections
    });

    const reportRef = db.collection('report_history').doc();
    await reportRef.set({
      reportId: reportRef.id,
      title: `Monthly Report - ${division}`,
      type: 'monthly',
      generatedBy: user.uid,
      generatedByName: user.fullName,
      division,
      periodStart: startStr,
      periodEnd: endStr,
      summary: {
        totalEvidence: evidenceDocs.length,
        contractors: Object.keys(contractorBreakdown).length,
        trains: Object.keys(trainBreakdown).length
      },
      generatedAt: admin.firestore.FieldValue.serverTimestamp()
    });

    return { pdfBuffer, filename: `MONTHLY_${division}_${endStr}.pdf` };
  }

  async getInvoicePdf(invoiceUid) {
    const doc = await db.collection('billingReports').doc(invoiceUid).get();
    if (!doc.exists) throw new NotFoundError('Billing report not found');
    const bill = doc.data();
    if (bill.status !== 'APPROVED' && !bill.invoiceNumber) {
      throw new ValidationError('Invoice not yet generated. Please generate invoice first.');
    }

    const invoiceNumber = bill.invoiceNumber || `INV-${invoiceUid.substring(0, 8)}`;
    const invoiceDoc = new PDFDocument({ margin: 50 });
    const buffers = [];

    return new Promise((resolve, reject) => {
      invoiceDoc.on('data', chunk => buffers.push(chunk));
      invoiceDoc.on('end', () => resolve({ pdfBuffer: Buffer.concat(buffers), filename: `invoice_${invoiceNumber}.pdf`, invoiceNumber }));
      invoiceDoc.on('error', reject);

      invoiceDoc.fontSize(22).fillColor('#1f4e78').text('SWACHH RAILWAYS', { align: 'center' });
      invoiceDoc.fontSize(10).fillColor('#666').text('Indian Railways – Swach Station Cleaning System', { align: 'center' });
      invoiceDoc.moveDown();
      invoiceDoc.fontSize(16).fillColor('#1f4e78').text('INVOICE', { align: 'center' });
      invoiceDoc.moveDown();

      invoiceDoc.fontSize(10).fillColor('#333');
      invoiceDoc.text(`Invoice Number: ${invoiceNumber}`);
      invoiceDoc.text(`Date: ${new Date(bill.invoiceGeneratedAt || new Date()).toLocaleDateString('en-IN')}`);
      invoiceDoc.text(`Period: ${bill.period || 'N/A'}`);
      invoiceDoc.moveDown();

      invoiceDoc.moveTo(50, invoiceDoc.y).lineTo(545, invoiceDoc.y).strokeColor('#ddd').stroke();
      invoiceDoc.moveDown();

      invoiceDoc.fontSize(12).fillColor('#1f4e78').text('Bill Details', { underline: true });
      invoiceDoc.moveDown(0.5);
      invoiceDoc.fontSize(10).fillColor('#333');
      const details = [
        ['Contract', bill.contractNumber || 'N/A'],
        ['Entity', bill.entityName || 'N/A'],
        ['Zone', bill.zone || 'N/A'],
        ['Division', bill.division || 'N/A'],
        ['Contract Value', `₹${(bill.contractValue || 0).toLocaleString('en-IN')}`],
        ['Overall Score', `${bill.overallScore || 0}%`],
        ['Grade', bill.grade || 'N/A'],
      ];
      details.forEach(([label, value]) => {
        invoiceDoc.text(`${label}: ${value}`, { continued: false });
      });
      invoiceDoc.moveDown();

      if (bill.deductions && bill.deductions.length > 0) {
        invoiceDoc.fontSize(12).fillColor('#1f4e78').text('Deductions', { underline: true });
        invoiceDoc.moveDown(0.5);
        invoiceDoc.fontSize(9).fillColor('#333');
        const tableTop = invoiceDoc.y;
        const col1 = 50, col2 = 200, col3 = 320, col4 = 420, col5 = 500;
        invoiceDoc.font('Helvetica-Bold');
        invoiceDoc.text('Type', col1, tableTop);
        invoiceDoc.text('Description', col2, tableTop);
        invoiceDoc.text('Count', col3, tableTop);
        invoiceDoc.text('Rate', col4, tableTop);
        invoiceDoc.text('Amount', col5, tableTop);
        invoiceDoc.font('Helvetica');
        let y = tableTop + 15;
        bill.deductions.forEach(d => {
          invoiceDoc.text(d.type || 'N/A', col1, y);
          invoiceDoc.text(d.description || 'N/A', col2, y);
          invoiceDoc.text(`${d.count || 0}`, col3, y);
          invoiceDoc.text(`₹${(d.rate || 0).toLocaleString('en-IN')}`, col4, y);
          invoiceDoc.text(`₹${(d.amount || 0).toLocaleString('en-IN')}`, col5, y);
          y += 15;
        });
        invoiceDoc.y = y;
      }
      invoiceDoc.moveDown();

      invoiceDoc.moveTo(50, invoiceDoc.y).lineTo(545, invoiceDoc.y).strokeColor('#ddd').stroke();
      invoiceDoc.moveDown();
      invoiceDoc.fontSize(14).fillColor('#28a745').text(
        `FINAL PAYABLE: ₹${(bill.finalPayable || 0).toLocaleString('en-IN')}`,
        { align: 'center' }
      );
      invoiceDoc.moveDown(2);

      invoiceDoc.fontSize(8).fillColor('#999').text(
        'Swachh Railways – Contractor Employee Portal | Indian Railways',
        { align: 'center' }
      );
      invoiceDoc.text(`Generated on ${new Date().toLocaleString('en-IN')}`, { align: 'center' });
      invoiceDoc.end();
    });
  }

  async getReports(user, query) {
    const { limit: queryLimit } = query;
    const limit = parseInt(queryLimit) || 50;
    const snapshot = await db.collection('report_history').orderBy('generatedAt', 'desc').limit(limit).get();
    const reports = [];
    snapshot.forEach(doc => reports.push({ id: doc.id, ...doc.data() }));
    return { count: reports.length, reports };
  }

  async getReportById(reportId) {
    const doc = await db.collection('report_history').doc(reportId).get();
    if (!doc.exists) throw new NotFoundError('Report not found');
    return { id: doc.id, ...doc.data() };
  }

  async deleteReport(reportId) {
    const doc = await db.collection('report_history').doc(reportId).get();
    if (!doc.exists) throw new NotFoundError('Report not found');
    await doc.ref.delete();
    return { message: 'Report deleted' };
  }

  async exportReport(reportId, format) {
    const doc = await db.collection('report_history').doc(reportId).get();
    if (!doc.exists) throw new NotFoundError('Report not found');
    return `/api/reports/${reportId}/export?format=${format || 'pdf'}`;
  }

  async getAttendanceAuditData(runInstanceId, workerId) {
    return this.legacyService.getAttendanceAuditData(runInstanceId, workerId);
  }

  async getOperationalAuditData(runInstanceId) {
    return this.legacyService.getOperationalAuditData(runInstanceId);
  }

  async getWorkerActivityAuditData(runInstanceId, workerId) {
    return this.legacyService.getWorkerActivityAuditData(runInstanceId, workerId);
  }

  async getComplaintAuditData(runInstanceId) {
    return this.legacyService.getComplaintAuditData(runInstanceId);
  }
}

export const reportService = new ReportService();
