import { stationReportService } from '../services/stationReportService.js';
import { autoEmailService } from '../services/autoEmailService.js';
import { asyncHandler } from '../middleware/errorHandler.js';

export const generateReport = asyncHandler(async (req, res) => { const { stationId, month, year } = req.body; res.status(201).json(await stationReportService.generateStationCleaningReport(stationId, month, year, req.user)); });
export const getReportById = asyncHandler(async (req, res) => res.json(await stationReportService.getReportById(req.params.uid)));
export const listReports = asyncHandler(async (req, res) => res.json(await stationReportService.listReports(req.query)));
export const getScoreTrend = asyncHandler(async (req, res) => res.json(await stationReportService.getStationScoreTrend(req.query.stationId, parseInt(req.query.months) || 6)));
export const getStationComparison = asyncHandler(async (req, res) => res.json(await stationReportService.getStationComparison(req.query.division, req.query.month, req.query.year)));
export const generateDailyAttendanceReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateDailyAttendanceReport(req.body.stationId, req.body.date, req.user)));
export const generateDailyActivityReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateDailyActivityReport(req.body.stationId, req.body.date, req.user)));
export const generateDailyScorecardReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateDailyScorecardReport(req.body.stationId, req.body.date, req.user)));
export const generateDailyComplaintReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateDailyComplaintReport(req.body.stationId, req.body.date, req.user)));
export const generateDailyFeedbackReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateDailyFeedbackReport(req.body.stationId, req.body.date, req.user)));
export const generateDailySupervisorLogReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateDailySupervisorLog(req.body.stationId, req.body.date, req.user)));
export const generateMissedActivityReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateMissedActivityReport(req.body.stationId, req.body.date, req.user)));
export const generateDailyInspectionReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateDailyInspectionReport(req.body.stationId, req.body.date, req.user)));
export const generateArchiveRetrievalReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateArchiveRetrievalReport(req.body.stationId, req.body.startDate, req.body.endDate, req.user)));
export const generateMonthlyAttendanceSummary = asyncHandler(async (req, res) => res.json(await stationReportService.generateMonthlyAttendanceSummary(req.body.stationId, req.body.month, req.body.year, req.user)));
export const generateMonthlyCleaningSummary = asyncHandler(async (req, res) => res.json(await stationReportService.generateMonthlyCleaningSummary(req.body.stationId, req.body.month, req.body.year, req.user)));
export const generateMonthlyScorecardSummary = asyncHandler(async (req, res) => res.json(await stationReportService.generateMonthlyScorecardReport(req.body.stationId, req.body.month, req.body.year, req.user)));
export const generateMonthlyComplaintSummary = asyncHandler(async (req, res) => res.json(await stationReportService.generateMonthlyComplaintSummary(req.body.stationId, req.body.month, req.body.year, req.user)));
export const generateMonthlyFeedbackSummary = asyncHandler(async (req, res) => res.json(await stationReportService.generateMonthlyFeedbackSummary(req.body.stationId, req.body.month, req.body.year, req.user)));
export const generateMonthlyBillingReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateMonthlyBillingReport(req.body.stationId, req.body.month, req.body.year, req.user)));
export const generateMonthlyPenaltyReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateMonthlyPenaltyReport(req.body.stationId, req.body.month, req.body.year, req.user)));
export const generateMonthlyPerformanceReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateMonthlyPerformanceReport(req.body.stationId, req.body.month, req.body.year, req.user)));
export const generateUserActivityAudit = asyncHandler(async (req, res) => res.json(await stationReportService.generateUserActivityAudit(req.query, req.user)));
export const generateImageArchiveReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateImageArchiveReport(req.query, req.user)));
export const generateRejectedFormsReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateRejectedFormsReport(req.query, req.user)));
export const generateInspectionHistoryReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateInspectionHistoryReport(req.query, req.user)));
export const generateDataModificationReport = asyncHandler(async (req, res) => res.json(await stationReportService.generateDataModificationReport(req.query, req.user)));
export const scheduleReport = asyncHandler(async (req, res) => res.status(201).json(await stationReportService.scheduleReport(req.body.reportType, req.body.cronExpression, req.body.recipients, req.body.parameters)));
export const listSchedules = asyncHandler(async (req, res) => res.json(await stationReportService.listSchedules(req.query)));
export const deleteSchedule = asyncHandler(async (req, res) => res.json(await stationReportService.deleteSchedule(req.params.uid)));
export const executeScheduledReports = asyncHandler(async (req, res) => res.json(await stationReportService.executeScheduledReports()));
export const getDailyReportTypes = asyncHandler(async (req, res) => res.json({ types: await stationReportService.getDailyReportTypes() }));
export const getMonthlyReportTypes = asyncHandler(async (req, res) => res.json({ types: await stationReportService.getMonthlyReportTypes() }));
export const getAuditReportTypes = asyncHandler(async (req, res) => res.json({ types: await stationReportService.getAuditReportTypes() }));
export const dispatchEndOfDayReports = asyncHandler(async (req, res) => res.json(await autoEmailService.dispatchEndOfDayReports(req.body.stationId, req.body.date || new Date().toISOString().split('T')[0])));
export const dispatchEndOfMonthReports = asyncHandler(async (req, res) => res.json(await autoEmailService.dispatchEndOfMonthReports(req.body.stationId, req.body.month, req.body.year)));
export const dispatchDailyReport = asyncHandler(async (req, res) => res.json(await autoEmailService.dispatchDailyReport(req.body.reportType, req.body.stationId, req.body.date || new Date().toISOString().split('T')[0])));
export const dispatchMonthlyReport = asyncHandler(async (req, res) => res.json(await autoEmailService.dispatchMonthlyReport(req.body.reportType, req.body.stationId, req.body.month, req.body.year)));
export const dispatchMissedActivityAlert = asyncHandler(async (req, res) => res.json(await autoEmailService.dispatchMissedActivityAlert(req.body.stationId, req.body.date || new Date().toISOString().split('T')[0])));
export const dispatchRejectedFormNotification = asyncHandler(async (req, res) => res.json(await autoEmailService.dispatchRejectedFormNotification(req.body.stationId, req.body.formType, req.body.formId, req.body.reason)));
export const dispatchComplaintEscalation = asyncHandler(async (req, res) => res.json(await autoEmailService.dispatchComplaintEscalation(req.body.complaintId, req.body.stationId, req.body.category, req.body.description)));
