import 'dart:typed_data';

import 'package:crm_train/model/station_cleaning_models.dart';
import 'package:intl/intl.dart';
import 'package:syncfusion_flutter_xlsio/xlsio.dart' as xlsio;

/// Generates an .xlsx workbook for any stored station-cleaning report.
/// Sheet 1 holds the report metadata + scalar KPIs + breakdown maps; each
/// array section of the summary gets its own labelled sheet with a table.
class StationReportExcelService {
  static const _navy = '#1A3E8C';
  static const _lightGray = '#F2F5F9';
  static const _altRow = '#EAF0F9';
  static const _white = '#FFFFFF';
  static const _gold = '#C8A400';

  static Future<Uint8List> generateStationReportExcel(
    StationReport report,
  ) async {
    final wb = xlsio.Workbook();
    final summary = report.summary;

    final scalarEntries = <MapEntry<String, dynamic>>[];
    final breakdownEntries = <MapEntry<String, Map<String, dynamic>>>[];
    final arrayEntries = <MapEntry<String, List<dynamic>>>[];

    summary.forEach((key, value) {
      if (value is Map) {
        breakdownEntries.add(MapEntry(key, Map<String, dynamic>.from(value)));
      } else if (value is List) {
        arrayEntries.add(MapEntry(key, value));
      } else {
        scalarEntries.add(MapEntry(key, value));
      }
    });

    _buildSummarySheet(wb, report, scalarEntries, breakdownEntries);
    _buildArraySheets(wb, report, arrayEntries);

    final bytes = wb.saveAsStream();
    wb.dispose();
    return Uint8List.fromList(bytes);
  }

  static void _buildSummarySheet(
    xlsio.Workbook wb,
    StationReport report,
    List<MapEntry<String, dynamic>> scalarEntries,
    List<MapEntry<String, Map<String, dynamic>>> breakdownEntries,
  ) {
    final s = wb.worksheets[0];
    s.name = 'Summary';
    s.getRangeByName('A1').setText('SWACHH RAILWAY - STATION CLEANING REPORT');
    s
        .getRangeByName('A2')
        .setText('${report.reportType} | ${report.stationName}');

    final titleStyle = wb.styles.add('title0')
      ..bold = true
      ..fontSize = 16
      ..fontColor = _navy;
    final subtitleStyle = wb.styles.add('title1')
      ..bold = true
      ..fontSize = 12
      ..fontColor = _gold;
    final metaStyle = wb.styles.add('meta')
      ..fontSize = 11
      ..backColor = _lightGray;
    final headerStyle = wb.styles.add('hdr')
      ..bold = true
      ..fontColor = _white
      ..backColor = _navy
      ..borders.all.lineStyle = xlsio.LineStyle.thin;
    final dataStyle = wb.styles.add('data')
      ..borders.all.lineStyle = xlsio.LineStyle.thin
      ..wrapText = true;

    s.getRangeByName('A1').cellStyle = titleStyle;
    s.getRangeByName('A2').cellStyle = subtitleStyle;

    final period =
        report.endDate != null &&
            report.endDate!.isNotEmpty &&
            report.endDate != report.date
        ? '${report.date} to ${report.endDate}'
        : report.reportType.startsWith('monthly_')
        ? '${report.month}/${report.year}'
        : report.date;

    s.getRangeByIndex(4, 1).setText('Station ID: ${report.stationId}');
    s.getRangeByIndex(4, 3).setText('Period: $period');
    s.getRangeByIndex(5, 1).setText('Generated By: ${report.generatedByName}');
    s
        .getRangeByIndex(5, 3)
        .setText(
          'Generated At: ${DateFormat('dd-MMM-yyyy hh:mm a').format(report.generatedAt.toLocal())}',
        );
    s.getRangeByIndex(4, 1, 5, 4).cellStyle = metaStyle;

    int row = 7;
    s.getRangeByIndex(row, 1).setText('KEY METRICS');
    s.getRangeByIndex(row, 1, row, 4).merge();
    s.getRangeByIndex(row, 1).cellStyle = headerStyle;
    row++;

    for (final e in scalarEntries) {
      s.getRangeByIndex(row, 1).setText(_formatLabel(e.key));
      s.getRangeByIndex(row, 1, row, 2).merge();
      s.getRangeByIndex(row, 3).setText('${e.value}');
      s.getRangeByIndex(row, 3, row, 4).merge();
      s.getRangeByIndex(row, 1, row, 4).cellStyle = dataStyle;
      row++;
    }

    for (final entry in breakdownEntries) {
      if (entry.value.isEmpty) continue;
      row++;
      s.getRangeByIndex(row, 1).setText(_formatLabel(entry.key).toUpperCase());
      s.getRangeByIndex(row, 1, row, 4).merge();
      s.getRangeByIndex(row, 1).cellStyle = wb.styles.add('hdr${entry.key}')
        ..bold = true
        ..fontColor = _white
        ..backColor = _navy
        ..borders.all.lineStyle = xlsio.LineStyle.thin;
      row++;
      s.getRangeByIndex(row, 1).setText('Item');
      s.getRangeByIndex(row, 3).setText('Value');
      s.getRangeByIndex(row, 1, row, 4).cellStyle = headerStyle;
      row++;
      for (final e in entry.value.entries) {
        s.getRangeByIndex(row, 1).setText(_formatLabel(e.key));
        s.getRangeByIndex(row, 1, row, 2).merge();
        s.getRangeByIndex(row, 3).setText('${e.value}');
        s.getRangeByIndex(row, 3, row, 4).merge();
        s.getRangeByIndex(row, 1, row, 4).cellStyle = dataStyle;
        row++;
      }
    }

    for (var c = 1; c <= 4; c++) {
      s.getRangeByIndex(1, c).columnWidth = c <= 2 ? 20 : 18;
    }
  }

  static void _buildArraySheets(
    xlsio.Workbook wb,
    StationReport report,
    List<MapEntry<String, List<dynamic>>> arrayEntries,
  ) {
    var sheetNo = 1;
    for (final entry in arrayEntries) {
      if (entry.value.isEmpty) continue;
      if (entry.key == 'feedbackComments' &&
          report.reportType.startsWith('daily_')) {
        continue;
      }
      final s = wb.worksheets.add();
      s.name = _sheetName(entry.key, sheetNo);
      sheetNo++;

      final unionKeys = <String>{};
      for (final r in entry.value) {
        if (r is! Map) continue;
        r.keys.forEach((k) => unionKeys.add('$k'));
      }
      final keys = unionKeys.take(10).toList();
      if (keys.isEmpty) continue;

      final headerStyle = wb.styles.add('ah${report.reportType}${entry.key}')
        ..bold = true
        ..fontColor = _white
        ..backColor = _navy
        ..borders.all.lineStyle = xlsio.LineStyle.thin;
      final altStyle = wb.styles.add('alt${report.reportType}${entry.key}')
        ..backColor = _altRow
        ..borders.all.lineStyle = xlsio.LineStyle.thin;
      final dataStyle = wb.styles.add('dt${report.reportType}${entry.key}')
        ..borders.all.lineStyle = xlsio.LineStyle.thin
        ..wrapText = true;

      s.getRangeByName('A1').setText(_formatLabel(entry.key));
      s
          .getRangeByName('A1')
          .cellStyle = wb.styles.add('ast${report.reportType}${entry.key}')
        ..bold = true
        ..fontSize = 14
        ..fontColor = _navy;

      for (var c = 0; c < keys.length; c++) {
        final cell = s.getRangeByIndex(3, c + 1);
        cell.setText(_formatLabel(keys[c]));
        cell.cellStyle = headerStyle;
      }

      var r = 4;
      for (final rec in entry.value) {
        if (rec is! Map) continue;
        for (var c = 0; c < keys.length; c++) {
          final cell = s.getRangeByIndex(r, c + 1);
          final v = rec[keys[c]];
          cell.setText(v is List ? v.toString() : '${v ?? ''}');
          cell.cellStyle = dataStyle;
          if (r.isEven) cell.cellStyle = altStyle;
        }
        r++;
      }

      for (var c = 0; c < keys.length; c++) {
        var maxLen = keys[c].length;
        for (final rec in entry.value) {
          if (rec is Map) {
            final v = rec[keys[c]];
            final txt = v is List ? v.toString() : '${v ?? ''}';
            if (txt.length > maxLen) maxLen = txt.length;
          }
        }
        s.getRangeByIndex(1, c + 1).columnWidth = (maxLen + 4)
            .clamp(8, 40)
            .toDouble();
      }
    }
  }

  static String _sheetName(String key, int no) {
    var name = key.replaceAll(RegExp('[^A-Za-z0-9 ]'), ' ');
    if (name.length > 25) name = name.substring(0, 25);
    return '$name ${no + 1}'.trim();
  }

  static String _formatLabel(String key) {
    final spaced = key.replaceAll(RegExp('([a-z])([A-Z])'), r'$1 $2');
    final withSpaces = spaced.replaceAll('_', ' ');
    if (withSpaces.isEmpty) return key;
    return withSpaces[0].toUpperCase() + withSpaces.substring(1);
  }
}
